### ISSUE TITLE
Problem running under Apache? or perhaps some bug?

### ISSUE THREAD

**Issue by unixhaj** [m0ngr31/kodi-alexa#1]
I'm not sure if this is a problem with running your code under Apache mod_wsgi or if it is an actual bug.

Some times it works when I use the skill, but other times I get this;
[wsgi:error] [pid 22558] [client 72.21.217.78:10552] mod_wsgi (pid=22558): Exception occurred processing WSGI script '/var/www/kodi-alexa/wsgi.py'.
[wsgi:error] [pid 22558] [client 72.21.217.78:10552] Traceback (most recent call last):
[wsgi:error] [pid 22558] [client 72.21.217.78:10552]   File "/var/www/kodi-alexa/wsgi.py", line 673, in application
[wsgi:error] [pid 22558] [client 72.21.217.78:10552]     output = h[1](environ, start_response)
[wsgi:error] [pid 22558] [client 72.21.217.78:10552]   File "/var/www/kodi-alexa/wsgi.py", line 643, in do_alexa
[wsgi:error] [pid 22558] [client 72.21.217.78:10552]     response = one_intent[1](intent_slots)
[wsgi:error] [pid 22558] [client 72.21.217.78:10552]   File "/var/www/kodi-alexa/wsgi.py", line 213, in alexa_play_pause
[wsgi:error] [pid 22558] [client 72.21.217.78:10552]     kodi.PlayPause()
[wsgi:error] [pid 22558] [client 72.21.217.78:10552]   File "/var/www/kodi-alexa/kodi.py", line 161, in PlayPause
[wsgi:error] [pid 22558] [client 72.21.217.78:10552]     playerid = GetPlayerID()
[wsgi:error] [pid 22558] [client 72.21.217.78:10552]   File "/var/www/kodi-alexa/kodi.py", line 65, in GetPlayerID
[wsgi:error] [pid 22558] [client 72.21.217.78:10552]     info = SendCommand(RPCString("Player.GetActivePlayers"))
[wsgi:error] [pid 22558] [client 72.21.217.78:10552]   File "/var/www/kodi-alexa/kodi.py", line 51, in SendCommand
[wsgi:error] [pid 22558] [client 72.21.217.78:10552]     return json.loads(r.text)
[wsgi:error] [pid 22558] [client 72.21.217.78:10552]   File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
[wsgi:error] [pid 22558] [client 72.21.217.78:10552]     return _default_decoder.decode(s)
[wsgi:error] [pid 22558] [client 72.21.217.78:10552]   File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
[wsgi:error] [pid 22558] [client 72.21.217.78:10552]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
[wsgi:error] [pid 22558] [client 72.21.217.78:10552]   File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
[wsgi:error] [pid 22558] [client 72.21.217.78:10552]     raise ValueError("No JSON object could be decoded")
[wsgi:error] [pid 22558] [client 72.21.217.78:10552] ValueError: No JSON object could be decoded

Funny thing is if I keep trying the request it will eventually work.
What do you think?

Oh, and thanks for what looks like a very nice skill - except for that problem I'm having:)

**Comment by m0ngr31** [comment]
What command are you trying? Is it only one that is struggling?

**Comment by unixhaj** [comment]
Actually it seems it might only be the pause/resume/play command that fails.
I'm watching a movie right now so will get back to you with result of further testing.

**Comment by m0ngr31** [comment]
Might be the way Amazon hears what you are saying. Try changing the utterance for a random word you can test.

**Comment by unixhaj** [comment]
Hey,

I solved my problem :) It seems it was a local problem with my kodi, and actually it was solved after restarting kodi.. :/ Didn't look there since it worked fine using the http control from both Yatse and the webinterface and kodi-send..

Might I suggest a feature that plays only movies that are not already seen ?

Again thanks for a very nice skill.

**Comment by m0ngr31** [comment]
Actually that's a pretty good idea. I was watching random episodes of a TV show today and got the same one once. Should be a pretty simple modification.

**Comment by m0ngr31** [comment]
I've updated it so it only pulls unwatched files now.
