### ISSUE TITLE
Problems deploying to AWS

### ISSUE THREAD

**Issue by sphirst** [m0ngr31/kodi-alexa#101]
I've followed all the steps detailed in your read me. I'm having some issues deploying to AWS - it hangs for quite some time while deploying then comes up with the following message.
Can you suggest where I am going wrong?

![image](https://cloud.githubusercontent.com/assets/25160581/21999123/6c1d1882-dc30-11e6-8ea6-c2a9570f7b4b.png)

**Comment by danielmasur** [comment]
We had this issue before. Can you please verify that your clock is correct?

**Comment by sphirst** [comment]
My time is set automatically and I've checked this against https://time.is/
All seems to be ok

**Comment by digiltd** [comment]
can you do a `dir` command on the directory and take a screenshot, also what command are you using to deploy?

**Comment by sphirst** [comment]
Using windows command prompt
![image](https://cloud.githubusercontent.com/assets/25160581/22000538/90bc7e74-dc37-11e6-9334-0a069a058eab.png)

**Comment by sphirst** [comment]
Using lambda-deploy

**Comment by digiltd** [comment]
https://github.com/m0ngr31/kodi-alexa#aws-variables

You should be using `python deploy-to-lambda.py`

But I think the clock issue is the problem, try adjusting your system clock 5 min either way.

**Comment by m0ngr31** [comment]
Just adjust your clock +/- 5 minutes until it works. The next version won't have this issue.
