### ISSUE TITLE
intent file error

### ISSUE THREAD

**Issue by ddemby** [m0ngr31/kodi-alexa#105]
hello.. i am having trouble uploading the intents to the alexa skills. Every time i attempt to submit, i get an error saying:

Error: There was a problem with your request: Unknown slot type 'MOVIEGENRES' for slot 'Genre'

please help....Thanks

**Comment by bill-orange** [comment]
I had the same problem today.  Ultimately I was successful.  Go back to the New Skills START button which is one step back.  Do not copy and paste alexa.intents and alexa.utterances on the following page.  Go to the next page where you set up the slots. Do not copy and paste alexa.intents and alexa.utterances.  Now, go ahead and set up your slots. Don't use the save on the bottom left.  Use the Save near Slots entry. You should not get any errors.  Enter all nine.  Be sure you did not miss one.  Now do your cutting and pasting of the two files and use the save on the bottom left.

I was beating my head against the wall before I found a warning in the GitHub instructions regarding this problem.

**Comment by jingai** [comment]
Yes, you should always do the Slots first, even when upgrading the skill (if any of the slots changed or new ones were added).

**Comment by belfastman36** [comment]
i have tried creating all slots still get that error  i dont have no music  on kodi tho i just made some up

**Comment by bill-orange** [comment]
Are you sure that when you hit save (the one in the middle of the page) that the paste alexa.intents and alexa.utterances boxes were blank?  One problem I had was hitting the wrong save button. 

Making up the song entries should no get you on much trouble.

**Comment by belfastman36** [comment]
KKK

**Comment by belfastman36** [comment]
hit this save as on screen
![20170206_050011](https://cloud.githubusercontent.com/assets/20203868/22635203/7d6015b4-ec29-11e6-8e92-1cc928a8c569.jpg)
![20170206_050011](https://cloud.githubusercontent.com/assets/20203868/22635219/a19a2e2e-ec29-11e6-9149-cec8b99e4a82.jpg)

**Comment by belfastman36** [comment]
can any one confirm  the names of all nine slots i need to use and do i enter the slot names in cap letters

**Comment by jingai** [comment]
The Slot names are exactly as listed in the README, and yes, they are all caps.

Take a screenshot of the Slots you've created.  Likely you've made a typo or something.

**Comment by bill-orange** [comment]
Have you tried using a different browser?  I have had problems with Internet Explorer when used on forms in recently written web sites. Just a thought. You might try the same process using FireFox.

**Comment by jingai** [comment]
Closing due to lack of response from submitter.
