### ISSUE TITLE
GlobalSearch Aeon MQ6 opens but does not pass the heard string

### ISSUE THREAD

**Issue by drunkcarni** [m0ngr31/kodi-alexa#106]
The voice command for search is working and command are issued correctly for Home, Globalsearch. But only GS open empty. Alexa response is fine: Searching for {Movie}. But the mask just stays open with no seach string entered.

Might be a problem with the Skin?

Thanks for the great skill btw, amazing what people can and are willing to do. Sharing with others is so much worth and I love the skill. Everybody is amazed that I can just start movies with my voice 👍

**Comment by GoGoJoe301** [comment]
Depends on what your trying to search, if local content it should be able to find with the default xonfluence skin (globalsearch addon) However this addon cannot search other addons. There would need to be a modifcation to the code to properly address an addon directly but even then i'm unsure if this gitbub code is cabable of doing so. It maybe that it only works with xonfluence... the default skin for kodi.. with that said it won't work with add on searches... someone would have to figure out how  to place the add ons in properly into the intent schema and utterances. I've tried but haven't been able to figure it out,

**Comment by jingai** [comment]
It is not/should not be skin-specific.  I use this function with Metropolis for instance with no issues.

All this function should require is that you have the GlobalSearch addon installed.

**Comment by GoGoJoe301** [comment]
Your saying your able to search add on metropolis with this code? If so what is your exact search string so that I may try. I cannot get Alexa to search anything besides xonfluence. It's even addressed directly in the github code: globalsearch addon.    I'm interested in how you've got metropolis to work without modifying. What is your search string?

**Comment by jingai** [comment]
No, I am saying I can search for anything you can search for with the Global Search addon.  It has nothing to do with xonfluence or any other skin, and everything to do with the Global Search addon.

**Comment by drunkcarni** [comment]
Yep, my initial issue was (or what I am trying to say):
with Aeon MQ6 on Kodi 16 and Global search installed I say the phrase:
Alexa, ask Kodi search for Shooter (example). 
my Kodi then present the global search window (mask and keyboard) but nothing is searched for. I mean the search window opens but nothing is shown else than the global search interface itself. I am not trying to search for an add on :)

**Comment by drunkcarni** [comment]
I will try with original skin or will reinstall Kodi (Joy oh Joy) ;)

**Comment by jingai** [comment]
I'm not sure why searching of addons was brought into the discussion, but.. for your original issue, I don't think it should depend on the skin, unless Aeon MQ6 is trying to do something clever with the Global Search addon that's interfering somehow.

I did just verify though: with the Metropolis skin, the search function works.

Definitely try with Estuary or Confluence first.  If it still doesn't work, perhaps you have some configuration issue in the Global Search addon?

**Comment by GoGoJoe301** [comment]
I guess I'm confused because when I say Alexa ask Kodi to search for ____ . No matter what I ask to search for Kodi responds alerting me she understands and repeats basically what I've asked. Then within Kodi Xonfluence search pops up stating no results founds (understandably so as xonfluence searches only local content). How do I get my Kodi to understand to use..Say Metalliq search via global search add on. I'm new to this and could really use some help understanding how to modify either settings within Kodi app or Alexa code.. whatever it takes to accomplish Alexa pulling up and searching through metalliq search vs this xonfluence with her search strings....

**Comment by jingai** [comment]
Again, this uses the Global Search addon.  I don't know what "metalliq search" is, and it shouldn't have anything to do with xonfluence or any other skin.

This Issue however is not related to what you're asking.

**Comment by GoGoJoe301** [comment]
Yes your correct, the issue I'm having and the OP are different. I assumed the same in the beginning... My bad. 

I'm sorry to highjack the post! Just thought it was a common problem. I don't know much about global search add-on but I do know the Alexa skill kit code here uses it. And for whatever reason it passes that along to xonfluence. Metalliq search is an add-on by repository q i have installed in my Kodi and I was hoping I could somehow get Alexa to pass her search strings there opposed to what's she innately does... Open xonfluence and fails 

Thank you for your knowledge on this

**Comment by jingai** [comment]
Install the Global Search addon and it will work.  If you have a request to support a different search addon, please make it a separate Issue.

**Comment by jingai** [comment]
I cannot reproduce this and haven't heard anything in a while, so I'm closing this.  Post here if you feel it's still an issue.
