### ISSUE TITLE
Play/Stop TV channels

### ISSUE THREAD

**Issue by grinsekatze003** [m0ngr31/kodi-alexa#110]
Hi there, is it possible to use this addon in order to play/stop tv channels? I'd love to do this, as I'm watching more tv than movies. like: Alexa, tell kodi to play BBC World News.

**Comment by mamiller90** [comment]
I'd really like to see this and looks as though it should be possible as you can get kodi to play a tv channell with the following:
``` bash
http://kodi-device/jsonrpc?request={"jsonrpc":"2.0","id":1,"method":"Player.Open","params":{"item":{"channelid":10}}}
```

where the  "channelid" for a channel can be found by doing the following which returns the "channelid", "label" and "uniqueid" for all tv channels:

``` bash
http://kodi-device:8080/jsonrpc?request={"jsonrpc": "2.0", "method": "PVR.GetChannels", "params": {"channelgroupid": "alltv", "properties" :["uniqueid"]},"id": 1}
```

So it looks as though you could do something similar to the play Movie intent where you ask alexa to play a channel "BBC 1" and we then look at all channels, find the channel with with label "BBC One", get the "channelid" then send the "Player.Open" request.

**Comment by freemans13** [comment]
There is a pull request that adds basic PVR capabilities. I must admit I've not kept it up to date with advances on trunk but it has the guts of what you need. It would be great if someone who has spare time to re-implement the pull request. I simply don't have time these days to do this :(

https://github.com/m0ngr31/kodi-alexa/pull/47

**Comment by mamiller90** [comment]
I didn't realise there was a pull request. I've just been messing around have have got basic functionality to ask alexa to play {channel}. I've not tested it fully as I'm not at home right now so have only used the service simulator when editing the alexa skill. I expect it's not going to work so well with certain channel names at the moment. Should I submit another pull request?

**Comment by jingai** [comment]
Added this as a suggested feature to the Projects page, so combined with the existing PR for PVR support, I believe that's enough to remind us.  I'm closing this Issue for now.
