### ISSUE TITLE
Help with Intent Schema and Utterances

### ISSUE THREAD

**Issue by GoGoJoe301** [m0ngr31/kodi-alexa#114]
So i'd like to play around with the code but i don't know enough about kodi or alexa to properly address the addon i want. I like Metalliq search as it allows me to search my youtube and usatv now add ons. within that one add on. however with your existing code it only allows xonfluence search (globalsearch addon)/ local content search only..... I've tried to modify the intent schema and utterances to address other addons to see if alexa would directly interact with those add ons... but haven't been successfully. Is there any chance i can get some assistance as to how i can exchange globalsearch addon for search to another 3rd party search like repository q's metalliq search that specializes in searching add ons. 

Thank you, and you guys have done a great job!

**Comment by jingai** [comment]
Please ask these sort of questions on the forum, as directed [here](https://github.com/m0ngr31/kodi-alexa#getting-help).

Issues on github are for bugs and feature requests.
