### ISSUE TITLE
Suggestions for invoking search add on

### ISSUE THREAD

**Issue by GoGoJoe301** [m0ngr31/kodi-alexa#115]
I'm not 100% how the request/ submit new issue thing works but I'm giving it a shot. I'm a fan of the skill you've developed however I'd like to able to use Alexa to invoke an add-on of my choosing for search.. (For example: Metalliq search made my repository q. That's installed on my Kodi ) Yes it's an add on to search other add ons content.. I understand that in the Alexa code globalsearch addon is specified for search. So the reaction is when I ask Alexa to search for something she pulls up xonfluence search where it always renders no results (because xonfluence only searches local content) 

I'd like to substitute globalsearch in my Alexa skill kit for metalliq Search some kind of way or perhaps maybe have global search redirect the string to metalliq Search vs defaulting to xonfluence.. I've tried messing with the intent schema etc... But no luck so far... I was wondering if I could get some help with adjusting my code so that instead of Alexa defaulting to xonfluence when i say "Alexa ask Kodi to search to the movie transformers" it's reaction is to open xonfluence to perform a local search. I'd like for it's reaction to be defaulting to metalliq search add-on to pass along the search strings... But I'm unsure of how to do this in the code.

Once again I apologize if I'm in the wrong forum or section or didn't ask the question in the right manor ..Just need some direction! Thank you .. appreciate all your doing!

**Comment by jingai** [comment]
I see what you're doing now.

We don't support piracy.

**Comment by GoGoJoe301** [comment]
Not sure why it was so hard for you to understand the first time I stated it in the other thread. And how dare you assume piracy because of multiple add-on search ... You have some nerve!

**Comment by jingai** [comment]
Nevermind. Just not going to get into this. 

Searching of add-ons is something that's on the list.

**Comment by GoGoJoe301** [comment]
Sad your all about judging first. I don't need your help ..  good luck being and asshole

**Comment by m0ngr31** [comment]
I'm not going to tolerate this kind of abuse. This thread is closed.
