### ISSUE TITLE
Pause Movie/TV Show

### ISSUE THREAD

**Issue by pr0fetul** [m0ngr31/kodi-alexa#119]
It seems that I cannot pause any on-playing movie/tv show. I can issue the command to play and stop, but not pause. 
I am using the skill through AWS Lambda, on a Raspberry Pi3. Everything else seems to working, except for Pause. 

Any ideas?

**Comment by jingai** [comment]
What happens when you say 'pause?'

Also, 'play' will pause as well if the media is currently playing (it's a toggle).

**Comment by pr0fetul** [comment]
Hi,

I will try with "play" instead of pause, I did not know it was a toggle.
When I say "Alexa, ask raspberry to pause" it blinks a couple of seconds
and then nothing. When I usually say "...Stop" it does stop the playback
and confirms.

Multumesc,
Vlad Chiriloiu
E-mail: vladchiriloiu@gmail.com
Phone: 0751131866

**Comment by jingai** [comment]
If it doesn't respond at all, and you see nothing in the cards, most likely she misunderstood you.  Go to the history in the Alexa app and tell us what she heard.

Either way, this isn't a problem with the skill -- Alexa simply isn't passing the command to the skill.

**Comment by pr0fetul** [comment]
Hi,

It seems you are right, however, "pause" asa word she understands quite
well in other queries as you can see in the screenshot. It's very odd why
only used in this skill it does not understand "pause" properly....

Multumesc,
Vlad Chiriloiu
E-mail: vladchiriloiu@gmail.com
Phone: 0751131866

**Comment by jingai** [comment]
What screenshot?

We have no control over what Alexa does with it before it is sent to the skill.  I couldn't tell you why she's not understanding correctly, but I can say that if you try repeatedly and provide feedback in the app when she does it correctly, it does help.

For example, try both of these repeatedly until it works, and then tell her it did what you want:

"Alexa, ask Kodi to pause"
"Alexa, tell Kodi to pause"

If you can't provide the screenshot, can you at least copy/paste the text here?  I'm curious to see what she heard instead.

**Comment by pr0fetul** [comment]
Here is the attachment again.

Multumesc,
Vlad Chiriloiu
E-mail: vladchiriloiu@gmail.com
Phone: 0751131866

**Comment by jingai** [comment]
Attachments don't come through to github for email replies.  We can't see the screenshot here.

**Comment by pr0fetul** [comment]
![screenshot_20170228-200139](https://cloud.githubusercontent.com/assets/17175289/23453901/e317edea-fe72-11e6-9093-bc19d454bb12.png)

Here is the screenshot attached here.. Hope it works now. 
I can confirm that issuing the command "Alexa, ask raspberry to play" works for both play and pause. 
However, it is very curious how she mis-understands pause only when triggering this skill.

**Comment by jingai** [comment]
Notice that "pause spotify" is two words -- that increases her accuracy.  It's the fact that in our case, pause is a single word.

Do what I said above, try both of these repeatedly until it works, and then tell her it did what you want:

"Alexa, ask Kodi to pause"
"Alexa, tell Kodi to pause" 

Try ennunciating in different ways until she gets one through, and then reward her for it by clicking the "Yes it did what I wanted" button in the app on that card.  Likewise, tell her "No" for the ones that were not correct.

I know it sounds odd.. but this does in fact help.

**Comment by digiltd** [comment]
You could also add a few more sample utterances for PlayPause.

In the **Interaction Model** section of the Alexa Skill scroll down the list of Sample Utterances and find:

```
PlayPause pause
PlayPause play
PlayPause resume
```

You could add:

```
PlayPause pause
PlayPause play
PlayPause resume
PlayPause pause playback
PlayPause pause video
PlayPause pause movie
PlayPause pause music
```

It seems like this is an isolated case of pause not being heard correctly, and maybe just adding a couple of more will fix it for you.

Be careful, don't go adding `play video, play song etc` as these will interfere with the "play song {songname} type intents"

**Comment by pr0fetul** [comment]
I added those and also updated the slots for Movies, TV Shows to have fresh entries as well. I will test the results tonight when I get home. 
I can confirm however that using play for both play and pause works. I will see tonight if the additions come int effect.

**Comment by jingai** [comment]
Fairly certain this is not an issue specific to this skill.
