### ISSUE TITLE
BucketAlreadyExists Error

### ISSUE THREAD

**Issue by DFranzen** [m0ngr31/kodi-alexa#122]
While following the lambda setup for version 2.5, I got the following error

BucketAlreadyExists: An error occurred (BucketAlreadyExists) when calling the CreateBucket operation: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.

After changing zappa_settings.json to
```
...
"s3_bucket": "<myusername>.kodi-alexa",
...
```

The deployment went without problems

**Comment by m0ngr31** [comment]
Yeah, that is my bad. I need to update the docs for that.
