### ISSUE TITLE
Error during python deploy-to-lambda.py command 

### ISSUE THREAD

**Issue by Jamelb** [m0ngr31/kodi-alexa#123]
File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.

**Comment by digiltd** [comment]
Have a look through the kodi forum thread http://forum.kodi.tv/showthread.php?tid=254502 

It is a common issue, search the thread for `NoRegionError`

**Comment by Jamelb** [comment]
Thank you!! That worked like a charm.
