### ISSUE TITLE
The remote endpoint could not be called, or the response it returned was invalid.

### ISSUE THREAD

**Issue by supernoober** [m0ngr31/kodi-alexa#124]
Annnd this is where I'm stuck.
"The remote endpoint could not be called, or the response it returned was invalid."
That is the output of using the service simulator to test the lambda function.
Did some searching, thought at first it could be an SSL issue but then read through these issues and saw that it can't be that.
I know i haven't missed a step or flubbed it. I started this process over from scratch at least 10 times.
Can anyone give me some pointers?

**Comment by supernoober** [comment]
found this in cloudwatch:
'value': KeyError Traceback (most recent call last): File "/var/task/wsgi.py", line 1932, in lambda_handler return on_intent(event['request'], event['session']) File "/var/task/wsgi.py", line 1899, in on_intent return one_intent[1](intent_slots) File "/var/task/wsgi.py", line 1298, in alexa_watch_movie heard_movie = str(slots['Movie']['value']).lower().translate(None, string.punc
'value': KeyError
Traceback (most recent call last):
File "/var/task/wsgi.py", line 1932, in lambda_handler
return on_intent(event['request'], event['session'])
File "/var/task/wsgi.py", line 1899, in on_intent
return one_intent[1](intent_slots)
File "/var/task/wsgi.py", line 1298, in alexa_watch_movie
heard_movie = str(slots['Movie']['value']).lower().translate(None, string.punctuation)
KeyError: 'value'

**Comment by digiltd** [comment]
Your best bet is to have a read through the kodi forum thread http://forum.kodi.tv/showthread.php?tid=254502 and then ask your question there.

But please don't just go the last page and add your question without having a look through first 😉

**Comment by jingai** [comment]
Aye, github is not a forum.
