### ISSUE TITLE
[German, non-English] Subtitle/audio stream confirmation output

### ISSUE THREAD

**Issue by jingai** [m0ngr31/kodi-alexa#126]
The replacement code for pycountry has support for English and French, but we currently only output English.

It'd probably be a good idea to add a field for German as well and output it based on the user's locale, since that is now a supported language.

**Comment by jingai** [comment]
There's a few other instances of English-only support in the skill too.  I've marked them with _XXXLANG_.

**Comment by jingai** [comment]
I really wish we could just import pycountry.. this is just adding to the translation nightmare, especially when we start supporting more languages..

**Comment by jingai** [comment]
Anyway, requests that use these just fail for German, btw.  We need to either a) catch unsupported languages and use English by default, or b) someone needs to add a 6th column to the dictionary for German.

**Comment by digiltd** [comment]
Here is the dict with a sixth column with German
 
https://github.com/digiltd/kodi-voice/blob/356046dd095011885a555e5cf7d1ea10a3f9f21c/kodi_voice/ISO-639-2_utf-8.txt

Not sure how to go about integrating it into kodi.py though, but hopefully it should help.

**Comment by jingai** [comment]
Already done :)  But thanks!

**Comment by jingai** [comment]
69d2c42 in kodi-voice should address this.  I tested locally by setting `language=de` but it'd be nice if someone else gave it a go.

**Comment by jingai** [comment]
If anyone wants to test, it's on the test pypi server, so you can do something like `pip install --upgrade --force-reinstall -i https://testpypi.python.org/pypi kodi-voice`

**Comment by jingai** [comment]
Seems it's working.  Will be in the next Kodi-Voice release.
