### ISSUE TITLE
Developer discussion

### ISSUE THREAD

**Issue by m0ngr31** [m0ngr31/kodi-alexa#129]
I was thinking it'd be nice to have a developer chat room for new features and quicker discussions than threads give. Does anyone have a preference on Slack vs Gitter?

**Comment by jingai** [comment]
No particular preference here honestly.

**Comment by Xaelias** [comment]
I would say slack myself not that my opinion matters much :-D

**Comment by m0ngr31** [comment]
Okay, I'll throw up a Slack channel.

**Comment by m0ngr31** [comment]
Okay, I've got one setup. Here's the link to get an invite: https://kodi-alexa-slack.herokuapp.com/

If we hit our limit on users/invites, we can switch to Gitter.

**Comment by jingai** [comment]
Might be worth putting this on the wiki?

**Comment by m0ngr31** [comment]
Probably

**Comment by jingai** [comment]
Added link in README in 522c6afca7232e5d751fa0d7ad1d3c7d4fd735f3

Eventually we should make use of the wiki, but this suffices for now.
