### ISSUE TITLE
No Longer Communicates

### ISSUE THREAD

**Issue by BarrieG14** [m0ngr31/kodi-alexa#132]
Hello,

I have been using this Skill for a few months now with no issues and I thank you for that in advance.

However now it no longer seems to communicate?   The Echo understands me and it comes up in the Alexa app that it knows what I have said but now I get the following errors:

Skill Response was marked as failure
Request Identifier: amzn1.echo-api.request.b3a273c8-423d-402d-9792-a107979dfb4e The target Lambda application returned a failure response

I also get Unexpected Communication issue
Request Identifier: amzn1.echo-api.request.f3320bd8-740e-4e42-a832-17e660197c7d There was a problem communicating with the requested skill

**Comment by jhayzkie88** [comment]
I'm having the same issue... help

**Comment by m0ngr31** [comment]
What version are you on?

**Comment by jhayzkie88** [comment]
17 Krypton... I was using the kodi Alexa skills last night and it was working fine... I came home today to watch but it's not working anymore.

**Comment by jhayzkie88** [comment]
@BarrieG14 I think I found the problem... check your kodi IP address 😁😁😁 for some reason mine changed... it's working for me now!!

**Comment by BarrieG14** [comment]
The public IP address changed for yours or on your private network?

**Comment by BarrieG14** [comment]
@m0ngr31 I'm on Kodi 15.2

**Comment by BarrieG14** [comment]
My Kodi is ob a raspberry Pi btw

**Comment by jingai** [comment]
If you don't have a static IP address, you need to as the README tells you:

```If you don't have a dedicated IP address, you'll need a dynamic DNS service to give you a static URL to use so you don't have to be constantly change this value.```

**Comment by BarrieG14** [comment]
So I ended up restarting from scratch but I cannot get it to create the Lambda function at all?
I get the following when I run python deploy-to-lambda.py

"Successfully installed fuzzywuzzy-0.15.0 gunicorn-19.7.1 pytz-2017.2 requests-2.
13.0 yaep-0.0.6
Starting new HTTPS connection (1): lambda.us-east-1.amazonaws.com

C:\Kodi\kodi-alexa-master>"

So I don't get the 'adding kodi-alexa-master lambda and the 'successfully deployed kodi-alexa-master'?
