### ISSUE TITLE
Unable To Create Lambda Function

### ISSUE THREAD

**Issue by BarrieG14** [m0ngr31/kodi-alexa#134]
So I ended up restarting from scratch (because I didn't add static url) but I cannot get it to create the Lambda function at all?
I get the following when I run python deploy-to-lambda.py

"Successfully installed fuzzywuzzy-0.15.0 gunicorn-19.7.1 pytz-2017.2 requests-2.
13.0 yaep-0.0.6
Starting new HTTPS connection (1): lambda.us-east-1.amazonaws.com

C:\Kodi\kodi-alexa-master>"

So I don't get the 'adding kodi-alexa-master lambda and the 'successfully deployed kodi-alexa-master'?

My .env file: https://pastebin.com/UM2eY9ER

**Comment by jingai** [comment]
Github isn't really a support forum, @BarrieG14 .  The Issues here are for tracking bugs in the software, not helping users set up the skill.

Your problem _may_ be a bug, but is likely not, so you should start by posting on the forum please.
