### ISSUE TITLE
[flask-ask] Behavior for AMAZON Standard Built-ins if not streaming music

### ISSUE THREAD

**Issue by jingai** [m0ngr31/kodi-alexa#140]
The handlers for [AMAZON.PauseIntent/NextIntent/PreviousIntent/StartOverIntent/ResumeIntent/etc](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/built-in-intent-ref/standard-intents) should probably default to controlling Kodi's own playback if nothing is currently streaming to the Echo.

The reason is, if we don't catch a particular utterance that Amazon does in their own built-ins, the skill will receive the AMAZON intent instead of the custom one we have, and simply tell the user it can't stream music or do nothing at all.

The music streaming currently works side-by-side with control of Kodi simply because we specify our own utterances as overrides if the skill was invoked with "ask/tell/etc Kodi".

But we can't guarantee we'll be in sync with Amazon's own list of utterances.. in fact, we probably never will be.

@digiltd mentioned this in chat on slack.  Provided you use the phrases we have in utterances.txt, there shouldn't be any collisions.. but I honestly think he's right:  we're going to end up having collisions.

His suggestion was to make a separate skill for streaming music.  I'm kind of inclined to agree with him after thinking it over more.  The music streaming code is all relatively self-contained, so it wouldn't be a massive ordeal to separate the two.

Additionally, it could actually be a benefit: the Kodi instance serving music could be independent.  So, you could keep a client running somewhere solely to serve music if you wanted to.

Plus we could get the basic playback control (for Kodi playback) utterances for free if we did split them up.

**Comment by digiltd** [comment]
It is true....?  Do we actually agree on something :)

But yes, separating into two Skills seems like a good idea

**Comment by jingai** [comment]
Aye, we do ;)

The big problem-in-the-middle is that we'd need to factor kodi.py out into a pip package or something, to avoid duplicating code.

**Comment by jingai** [comment]
It's been decided to branch flask-ask off to streaming-music and remove the streaming code from flask-ask for now.
