### ISSUE TITLE
kodi-alexa Skill on own Apache2 WebServer

### ISSUE THREAD

**Issue by sveni-lee** [m0ngr31/kodi-alexa#144]
hello,

I try to test kodi-alexa Skill onmy own Apache2 Server but I can't get it work.
I allways get the following Error:

`The remote endpoint could not be called, or the response it returned was invalid.`
`Parse error on line 1:
The remote endpoint
^
Expecting 'STRING', 'NUMBER', NULL,TRUE, FALSE, '{', '[', got
'undefinined'`

the Server has an SSL Certificate and I can reach him from outside... I realy don't know what I'm doing wrong...

**Comment by jingai** [comment]
Please post support requests on the forum.  Github is for discussing issues with the code.
