### ISSUE TITLE
Planned new commands

### ISSUE THREAD

**Issue by jingai** [m0ngr31/kodi-alexa#15]
I'm planning on implementing support for the following.  I figured it was worthwhile to make the list public so as to avoid overlapping work if you're already working on any of them and to discuss implementation details.

**Power commands**
- [x] System.Hibernate
- [x] System.Reboot
- [x] System.Shutdown
- [x] System.Suspend
- [ ] Application.Quit

**Misc commands**
- [x] System.EjectOpticalDrive
- [x] Application.SetMute
- [x] GUI.SetFullscreen
- [ ] Application.SetVolume

**Addon commands**
- [ ] Addons.GetAddons (to fetch list to match against slot)
- [ ] Addons.ExecuteAddon

**Player commands**
- [x] Player.SetSubtitle (e.g., "Alexa, tell kodi enable/disable/toggle/turn on/turn off subtitles", "Alexa, tell kodi to use/switch to next/previous subtitle")
- [x] Player.SetAudioStreem (e.g., "Alexa, tell kodi to use/switch next/previous audio stream/language")
- [ ] Player.Seek

**Comment by m0ngr31** [comment]
I suggest that we setup a `feature` branch that we can both work off of, so we don't have so many conflicts. I love these suggestions (I'll need to update the node server if we are going to be making too many more slots though. That nested call thing is a mess).

I'll give you write access to the repo so you don't have to keep submitting PRs.

**Comment by Xaelias** [comment]
I'm sad to say I said to myself I would implement some of these months ago... and still have not done anything ><

I'll try to help if I can! At least I can help code review ><

**Comment by jingai** [comment]
A feature branch sounds good.  Keep this Issue open and we can tick things off as we go, unless you have another way you want to track progress.

Of the things I listed, I think only one (Addons) will require another slot.

**Comment by m0ngr31** [comment]
I added these features to the "Projects" board. That'll give us an easy place to keep things straight and a good place for people to suggest new things. I added you as a contributor, so you should be good to commit directly to the repo.

**Comment by jingai** [comment]
Ok, I'll still push features up on individual branches though so you get a chance to at least look at it before it goes into master.  Mostly because I just use WSGI here, so it's possible I could break something with Lambda/Docker/etc, though unlikely with these particular changes.

**Comment by Xtropy74** [comment]
A few suggestions:

Play a random (genre) movie. IE: Play a random comedy movie
Play a random new movie. IE: Play a random unwatched movie
Play a random movie.  IE: Play a random movie from the entire collection (currently defaults to unwatched)
What new movies do I have. IE: Voice response (like episodes) for unwatched movies

Finally:
Inquiries for movies/TV shows in a collection. Such as "Alexa, ask Kodi if I have Die Hard" and have her respond that the movie/show is in the library/collection.

Thanks for the amazing work on this. Just wanted to throw out a few suggestions....

**Comment by jingai** [comment]
@Xtropy74, Good suggestions.  I'll look into these.

**Comment by m0ngr31** [comment]
I had playing a random genre of movie/tv show working on my last laptop, but I didn't ever commit it. I need to clean up the slot generator anyways, so what's a few more slots?

**Comment by jingai** [comment]
This is all in Projects now, so closing this.
