### ISSUE TITLE
Quit does not work using POST

### ISSUE THREAD

**Issue by vtebano** [m0ngr31/kodi-alexa#157]
With the current code I can not get the quit kodi command to work.  I did however get the Application.Quit to work using a Get command in postman.
The command below works:
http://<Your IP>:<Your Port>/jsonrpc?request={"jsonrpc": "2.0", "method": "Application.Quit", "id":1}

I tried to update the kodi.py file to use this but my python is up to par yet.

**Comment by jingai** [comment]
Set SHUTDOWN_MEANS_QUIT=1 in .env for this. You cannot tell Alexa to "tell Kodi to quit" because she interprets that to mean you want the skill to quit. After you set the variable above, you can say, "tell Kodi to shut down" and Kodi will quit.

**Comment by vtebano** [comment]
I have SHUTDPWN_MEANS_QUIT=1.  Alexa says its shutting down but nothing happens.

**Comment by jingai** [comment]
"Alexa, tell Kodi to shut down" should respond with, "Are you sure?"

If you answer with an affirmative, it will send Application.Quit to Kodi.  If it's not actually doing it, you need to first check that Alexa heard you properly in the history in the Alexa app.

Also, github is not really the place for technical support.  As the README states, please post questions to the forum.
