### ISSUE TITLE
Idea: instructions for creating venv for specific version

### ISSUE THREAD

**Issue by Wholteza** [m0ngr31/kodi-alexa#159]
Hi. I think adding the command for making a virtualenv with python2.7 as the specific version is a good idea. If the user's not that familiar with python, having python 3 installed on the same machine for another project can really screw things up. It did for me, and i am used to using both python, flask and linux( i just didn't think of it). 

Ex: Using "virtualenv venv" on a machine with both python 2.x and 3.x installed will usually make a python 3.x environment. And because the flask package and the rest of the code in this project is made for 2.7, that fucks things up :P .

Not as a complaint. I just think it's a good idea since you already have a 99% foolproof guide, why not make it 100% :)

Anyways, works great for me, thank you!
Much love!

**Comment by jingai** [comment]
It's a valid point.  A lot of users get tripped up by this.

**Comment by m0ngr31** [comment]
It's hard to know since every OS is different. On Ubuntu, 2.7 is still the default, and the setup specifically states to use 2.7.

**Comment by jingai** [comment]
Aye, but for some reason quite a lot of people seem to miss it.  Maybe we should just make it more prominent?

**Comment by m0ngr31** [comment]
Yeah, we can make it bold or did you have something else in mind?

**Comment by jingai** [comment]
Maybe just make it a bulleted list in the Initial Computer Setup section (to make it stand out better) and add a comment to explicitly state that Python 3 won't work?  I'm honestly not sure why exactly people seem to miss it, but it could be that they don't understand the significance of the distinction between 2.7 and 3.

As an aside, is Python 2.7 still a hard requirement for this?  Besides the fact that the skill code itself needs some adjustments to move to Python 3?

**Comment by m0ngr31** [comment]
I'd have to look specifically at the deps we're using, so I can't give a good answer on if 3 would work or not. I'm sure it'd make UTF-8 character handling easier.

**Comment by m0ngr31** [comment]
I updated the README so I'll close this issue.
