### ISSUE TITLE
Application.Quit

### ISSUE THREAD

**Issue by jingai** [m0ngr31/kodi-alexa#16]
Unable to add a Quit intent to quit Kodi, because Amazon intercepts quit, exit, and close as requests to end the session.

Unless someone can think of an alternate way to invoke this, we'll probably have to settle for just Shutdown (which can be mapped in Kodi to Quit).

**Comment by jingai** [comment]
Hmm, apparently Kodi doesn't respect the user's configured action for Shutdown when called via JSON RPC.  Annoying.

**Comment by jingai** [comment]
I think the problem is that the "quit" utterance is reserved to tell the skill itself to quit (i.e., SessionEndedRequest).  We could intercept this under certain conditions, like maybe if 'reason' is 'USER_INITIATED' and quit Kodi, but once we start supporting keeping sessions open, this might lead to accidentally quitting Kodi if the user is just trying to tell the skill to stop talking to them.

Of course, we could just check to see if the session is currently open and map it accordingly.  Would have to think it through is all.

Another approach would be to make the action of the shutdown intent configurable via an environment variable.  On my local branch I currently map shut down to quit for this reason, but it'd be easy enough to make it configurable so all could use it if they choose to.

Anybody have any particular preference?

**Comment by fonzie24** [comment]
I notice you have many power commands, such as: "Hibernate, Reboot, Shutdown, Suspend"

However, I was wondering if it would be possible to add an intent to log off a user profile?

I tried to do it myself, but I couldn't get it to work.

I have multiple user accounts and it would be helpful to have a voice command to quickly log off the current user to make sure the watched statuses get synched correctly (among other things).

**Comment by jingai** [comment]
@fonzie24 , open a separate Issue please and we'll see what we can do.

**Comment by jingai** [comment]
I'm probably going to make this configurable via an environment variable unless anyone objects.

**Comment by jingai** [comment]
Just reminding myself to take care of #17 at the same time.
