### ISSUE TITLE
name matching for artists

### ISSUE THREAD

**Issue by mcl22** [m0ngr31/kodi-alexa#162]
The skill seems to have some issues with sepcial artist names. So far I've found the following problems:

1. german umlauts / special characters
The skill matches the right artist but then seems to have a ascii/utf8(unicode) problem. For instance, if I telll Alexa to play "böhse Onkelz" the log tells a simple match on direct comparison but then states::
UnicodeEncodeError: 'ascii' codec can't encode character u'\\xf6' in position 17: ordinal not in range(128)
The same happens with Céline Dion (with another character). Also for "die Schlümpfe" or "Abstürzende Brieftauben".

2. artists with single characters
Examples here are "Der W" or "Boney M.". When asking Alexa to play those, she instead starts PartyPlay.

3. artists with numbers in their names
For 2Pac, Alexa understands Tupac. Well that's not that wrong actually but of course it can't match 2Pac. But when trying artists like "2unlimited" or "blink-182" she only tells me that she couldn't find "none".

And, for that the headline on this topic is not completely right, I also have problems with numbers in albums. I've found a really special one. The album is called "Sex Sex Sex" by artist J.B.O.. This album even is an entry in the MUSICALBUMS slot. But the skill can't find it because Alexa searches for "Sechs Sechs Sechs" which is the german word for six.

**Comment by jingai** [comment]
For your second and third issues, let's take care of your original problem first, as I suspect you're seeing those issues because your slot isn't 'generic.'  That is, in your case, I don't think the fuzzy matching code is executing.  This is supposed to handle things like your "sex sex sex" issue, where Alexa hears words you didn't intend.

I'll continue helping you on the forums with this since we started there, unless everyone wants to move the discussion to Github.  But it probably should be at least a new Issue ("German skill fails to generate")

**Comment by jingai** [comment]
I believe points 2 and 3 are non-issues -- at least not issues beyond the already known limits of the fuzzy matching.  The OP also has the issue reported in #163 and at one point ended up with a list of artists that was too short to promote the slot to 'generic', which I'm sure exacerbated the problems with matching.

@mcl22, could you please provide more of the log file around the error you describe in point 1?

**Comment by mcl22** [comment]
I tried a lot of artitsts with umlauts in their names. The result is always this ascii error. Here is an example:
asking for "Böhse Onkelz"
log:
[wsgi:error] [pid 4188:tid 1268] Searching for artist "bohse onkelz"
[wsgi:error] [pid 4188:tid 1268] Sending request to http://***.***.***.***:*****/jsonrpc from device amzn1.ask.device.***
[wsgi:error] [pid 4188:tid 1268] Trying to match: bohse onkelz
[wsgi:error] [pid 4188:tid 1268] Simple match on direct comparison
[wsgi:error] [pid 4188:tid 1268] [amz srv] [2017-05-18 08:34:58,125] ERROR in app: Exception on / [POST]
[wsgi:error] [pid 4188:tid 1268] [amz srv] Traceback (most recent call last):
[wsgi:error] [pid 4188:tid 1268] [amz srv]   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1982, in wsgi_app
[wsgi:error] [pid 4188:tid 1268] [amz srv]     response = self.full_dispatch_request()
[wsgi:error] [pid 4188:tid 1268] [amz srv]   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1614, in full_dispatch_request
[wsgi:error] [pid 4188:tid 1268] [amz srv]     rv = self.handle_user_exception(e)
[wsgi:error] [pid 4188:tid 1268] [amz srv]   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1517, in handle_user_exception
[wsgi:error] [pid 4188:tid 1268] [amz srv]     reraise(exc_type, exc_value, tb)
[wsgi:error] [pid 4188:tid 1268] [amz srv]   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1612, in full_dispatch_request
[wsgi:error] [pid 4188:tid 1268] [amz srv]     rv = self.dispatch_request()
[wsgi:error] [pid 4188:tid 1268] [amz srv]   File "C:\\Python27\\lib\\site-packages\\flask\\app.py", line 1598, in dispatch_request
[wsgi:error] [pid 4188:tid 1268] [amz srv]     return self.view_functions[rule.endpoint](**req.view_args)
[wsgi:error] [pid 4188:tid 1268] [amz srv]   File "C:\\Python27\\lib\\site-packages\\flask_ask\\core.py", line 594, in _flask_view_func
[wsgi:error] [pid 4188:tid 1268] [amz srv]     result = self._map_intent_to_view_func(self.request.intent)()
[wsgi:error] [pid 4188:tid 1268] [amz srv]   File "C:/***/htdocs/kodi-alexa\\alexa.py", line 599, in alexa_listen_artist
[wsgi:error] [pid 4188:tid 1268] [amz srv]     artist, artist_label = kodi.FindArtist(heard_artist)
[wsgi:error] [pid 4188:tid 1268] [amz srv]   File "C:\\Python27\\lib\\site-packages\\kodi_voice\\kodi.py", line 483, in FindArtist
[wsgi:error] [pid 4188:tid 1268] [amz srv]     print 'Located artist "%s"' % (located['label'])
[wsgi:error] [pid 4188:tid 1268] [amz srv] UnicodeEncodeError: 'ascii' codec can't encode character u'\\xf6' in position 17: ordinal not in range(128)

And that happens for all the artists with umlauts:
"Hans Söllner"
UnicodeEncodeError: 'ascii' codec can't encode character u'\\xf6' in position 22: ordinal not in range(128)
"Herbert Grönemeyer"
UnicodeEncodeError: 'ascii' codec can't encode character u'\\xf6' in position 26: ordinal not in range(128)
"Die Ärzte"
UnicodeEncodeError: 'ascii' codec can't encode character u'\\xc4' in position 20: ordinal not in range(128)
"Abstürzende Brieftauben"
UnicodeEncodeError: 'ascii' codec can't encode character u'\\xfc' in position 20: ordinal not in range(128)
and so on

Please tell me if you need more information or log data.

**Comment by jingai** [comment]
Nope, that's all I needed. It's an easy fix.
