### ISSUE TITLE
Cannot complete setup

### ISSUE THREAD

**Issue by pr0fetul** [m0ngr31/kodi-alexa#166]
Hi, 

Awesome work. However, it seems I have an issue, I have Python 2.7 installed as per instruction, I have installed the virtual environment. Then I download the kodi-alexa zip, unzip-it on my C drive - other location than Python/Scripts, access it from CMD - ran:
C:\Alexa codes\kodi-alexa>C:\Python27\Scripts\virtualenv venv
C:\Alexa codes\kodi-alexa>venv\Scripts\activate.bat
it gives me:
(venv) C:\Alexa codes\kodi-alexa>
and when I try to run: **pip install -r requirements.txt** it gives me an error:
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

Do you know what I am missing? Where I am going wrong? It seems as I am not in the right folder, although in the kodi-alexa folder, there is a requirements.txt file...

Any help is welcomed. 
Thank you

**Comment by jingai** [comment]
Please ask for support on the forums, as [the README states](https://github.com/m0ngr31/kodi-alexa#getting-help).
