### ISSUE TITLE
Feature request (ListenToLatestAlbum)

### ISSUE THREAD

**Issue by mcl22** [m0ngr31/kodi-alexa#167]
I'dont know if this is possible. But in most cases I don't know the (exact) album titles and just want to listen to the newest one. So I'd really love to have a function like "Alexa, play the latest album by Rammstein".

**Comment by jingai** [comment]
It should be possible, provided we can do it without colliding with one of the many other utterances for music :)

**Comment by jingai** [comment]
I've got this working, but it required trimming the slot items even further.  Before I settle on a value, I'm going to look at what we can trim from the German utterances and then see what number of slot items we can fit there too.

**Comment by jingai** [comment]
I've reduced the number of slot items to 150 each and they still go 'generic'.  Going to settle on that number for now since the German skill appears to be a bit closer to the cap (size?).

**Comment by jingai** [comment]
@mcl2, while I have you here.. I do have a few new strings that need translating:

```
could_not_find_artist: "Could not find anything by {{ artist_name }}"
playing_latest_album_card: "Playing latest album by {{ heard_artist }}"
shuffling_latest_album_card: "Shuffling latest album by {{ heard_artist }}"
```

The new utterances for these are (in English):

```
ListenToLatestAlbum (play/listen to) (/the) (latest/newest) album by {Artist}
ShuffleLatestAlbum shuffle (/the) (latest/newest) album by {Artist}
```

**Comment by mcl22** [comment]
"Could not find anything by {{ artist_name }}"
"Konnte nichts von {artist_name} finden" (general)
"Konnte keine Lieder/Musik von {artist_name} finden" (refering to songs/music)

"Playing latest album by {{ heard_artist }}"
"Spiele zuletzt hinzugefügtes Album von {hear_artist}"

"Shuffling latest album by {{ heard_artist }}"
"Zufallswiedergabe des zuletzt hinzugefügten Albums von {heard_artist}"

ListenToLatestAlbum spiele das (neueste/aktuellste/neue/aktuelle) Album von {Artist}
ListenToLatestAlbum spiele (aktuelles/neues/neuestes/aktuellstes) Album von {Artist}
ListenToLatestAlbum spiele zuletzt hinzugefügtes Album von {Artist}
ListenToLatestAlbum spiele zuletzt das hinzugefügte Album von {Artist}

ShuffleLatestAlbum shuffle (/starte) Zufallswiedergabe des (aktuellen/neuen/aktuellsten/neuesten/zuletzt hinzugefügten) Albums von {Artist}

**Comment by jingai** [comment]
Appreciate it!

**Comment by jingai** [comment]
This is implemented now.  Going to wait until we sort out #163 though to release it.

**Comment by jingai** [comment]
Kodi-Alexa 2.6.2 released and includes a fix for this.
