### ISSUE TITLE
Destructive commands should require confirmation

### ISSUE THREAD

**Issue by jingai** [m0ngr31/kodi-alexa#17]
Hibernate, Reboot, Shutdown, Suspend.

Since they can be destructive (loss of user's work in other applications), Alexa should probably prompt with "Are you sure you want to do this?".  But this requires keeping track of the session, which we don't currently do.

**Comment by m0ngr31** [comment]
I just commited some code to play with saving the session data, so this is something we can start looking at.

**Comment by jingai** [comment]
I'll fool around with it more after we've merged the flask-ask branch.  I want [Quit](https://github.com/m0ngr31/kodi-alexa/issues/16) to work too, which is somewhat related.  Currently I just maintain local changes to make Shutdown function as Quit.
