### ISSUE TITLE
artist vs. album artist

### ISSUE THREAD

**Issue by mcl22** [m0ngr31/kodi-alexa#170]
I don't know if this is possible or if it only depends on the settings in kodi. But if you choose to just show album artists in kodi ( Settings > Media > Music) to have your library more organized then Alexa won't find songs performed by artists who only appear on sampler albums (various artists) when asking her to "play song by artist".

**Comment by jingai** [comment]
The Kodi JSON-RPC docs for AudioLibrary.GetArtists albumartistsonly field is worded a little funny.  It states:

```
[ Optional.Boolean albumartistsonly ] Whether or not to only include album artists rather than the artists of only individual songs as well. If the parameter is not passed or is passed as null the GUI setting will be used
```

Someone correct me if I'm wrong, but I _think_ that's saying:

1) If omitted, use the GUI setting,
2) If True, only return album artists,
3) If False, return all artists.

If I'm reading it correctly.. I think #3 would provide the behavior the OP is looking for.

**Comment by mcl22** [comment]
Sounds great. And I think the skill should always search all artists, shouldn't  it.

**Comment by jingai** [comment]
I suppose that's a matter of opinion.. and is why it's an optional thing both in Kodi and via JSON-RPC :)

I'm ok with adding `albumartistsonly=False` though, if no one else objects?

edit: sorry, meant _False_.. typed it in a hurry.

**Comment by jingai** [comment]
@digiltd and @m0ngr31 could you test a little with the `albumartistsonly` parameter set to `False`?  I actually don't have any such songs in my library, as I prefer to collect only full albums.

**Comment by jingai** [comment]
FWIW, it works for me here with this change.  If I get no objections, I'll push it up on Sunday or so.

**Comment by jingai** [comment]
Kodi-Alexa 2.6.2 released and includes a fix for this.
