### ISSUE TITLE
Feature Suggestion selectable modules

### ISSUE THREAD

**Issue by ScriptSorcererUK** [m0ngr31/kodi-alexa#174]
As this skill is getting a bit big because of all the features: how about having TV, Movies, Music and Music Video all as different options that you can enable or disable when building (with a maximum of 2 allowed). Then if you don't use Kodi for say music, you can choose not to use it. Should make everything quicker and smaller. If someone wanted more than two, they can export it as two different skills ie "Alexa ask video kodi..." and "Alexa ask video kodi". 

Maybe even each section could be broken down into components you can enable or disable,  such as if you never search by artist, you can choose not to add it in...

**Comment by jingai** [comment]
You can already get what you want easily enough without any changes to the code-base.

Simply remove Intents (and their corresponding Utterances) you don't want -- that's it.

Cutting out the code from the skill isn't going to give you the boost in speed that you think it will.  The individual intent handlers aren't all that large, and they're not executed if they're not relevant to your request.

The biggest gain you can achieve is simply by cutting the size of the interaction model (the thing you build on Amazon's dev site).  If you don't want any of the music stuff, for instance, delete everything that begins with `ListenTo` in both IntentSchema.json and SampleUtterances.txt.
