### ISSUE TITLE
Slot doesn't get generic (german version)

### ISSUE THREAD

**Issue by mcl22** [m0ngr31/kodi-alexa#175]
I thought I would open a new issue for that. Especially because of the behaviour I figured out as described in #163.
I now have a pretty good example of the strange behaviour I faced:
I do have these movies in my library: Rambo, Rambo II - Der Auftrag, Rambo III, John Rambo
My MOVIES sample only include: Rambo (150 items at all)
My utterances for WatchMovie are:
WatchMovie zeig Film {Movie}
WatchMovie zeig den Film {Movie}
WatchMovie zeige Film {Movie}
WatchMovie zeige den Film {Movie}

If I try to watch "Rambo", it works. If I try to watch "John Rambo", it also plays "Rambo". That's for utterances.
But if I now say "spiele den Film John Rambo" it works ("zeig(e)" means "show" / "spiel(e)" means "play")! 
Funnily it only works when saying "spiele" not "spiel" what actually means the same. And by saying it works I really mean it works all the time.

One could now think, ok let's add "WatchMovie spiele den Film {Movie}" to the utterances. But if I do that, it won't work any more and instead play "Rambo".

I'm not quite sure what to think about that. I'm willing to go through the german utterances and modify them (and I already did that for a lot of them). But now I don't know in what way I should update them. Choose verbs you'd never say, so it would do the right thing :)

**Comment by jingai** [comment]
First off, without logs, I can't be sure if the problems you're describing have anything to do with the slot's generic status or not.

There are a few different code-paths for things depending on how you asked for it.  I need to see what the skill says in each instance to help you diagnose your problem.

For each test, I specifically need:

1) Exactly what you said to Alexa,
2) The skill logs from the server.

**Comment by jingai** [comment]
Opened #176 to address the issue with slots going generic.  Closing this -- if you want further help with your matching problems, please post to the forum.

**Comment by mcl22** [comment]
I said: "öffne kodi und zeig film john rambo"
alexa: "alexa öffne kodi und zeig film rambo"
log: 
Spiele Film
 Searching for movie "Rambo"
 Sending request to http://127.0.0.1:8081/jsonrpc from device amzn1.ask.device.AH***
 Trying to match: rambo
 Simple match on direct comparison
 Located movie "Rambo"
 Sending request to http://127.0.0.1:8081/jsonrpc from device amzn1.ask.device.AH***
 Sending request to http://127.0.0.1:8081/jsonrpc from device amzn1.ask.device.AH***

I said: I said: "öffne kodi und zeige film john rambo"
alexa: "öffne kodi und zeige film rambo"
log:
Spiele Film
 Searching for movie "Rambo"
 Sending request to http://127.0.0.1:8081/jsonrpc from device amzn1.ask.device.AH***
 Trying to match: rambo
 Simple match on direct comparison
 Located movie "Rambo"
 Sending request to http://127.0.0.1:8081/jsonrpc from device amzn1.ask.device.AH***
 Sending request to http://127.0.0.1:8081/jsonrpc from device amzn1.ask.device.AH***

I said: I said: "öffne kodi und zeig den film john rambo"
alexa: "alexa öffne kodi und zeig den film rambo"
log:
Spiele Film
 Searching for movie "Rambo"
 Sending request to http://127.0.0.1:8081/jsonrpc from device amzn1.ask.device.AH***
 Trying to match: rambo
 Simple match on direct comparison
 Located movie "Rambo"
 Sending request to http://127.0.0.1:8081/jsonrpc from device amzn1.ask.device.AH***
 Sending request to http://127.0.0.1:8081/jsonrpc from device amzn1.ask.device.AH***

I said: I said: "öffne kodi und zeige den film john rambo"
alexa: "öffne kodi und zeige den film rambo"
log:
 Spiele Film
 Searching for movie "Rambo"
 Sending request to http://127.0.0.1:8081/jsonrpc from device amzn1.ask.device.AH***
 Trying to match: rambo
 Simple match on direct comparison
 Located movie "Rambo"
 Sending request to http://127.0.0.1:8081/jsonrpc from device amzn1.ask.device.AH***
 Sending request to http://127.0.0.1:8081/jsonrpc from device amzn1.ask.device.AH***

I said: I said: "öffne kodi und spiele den film john rambo"
alexa: "alexa öffne kodi und spiele den film john rambo"
log:
 Spiele Film
 Searching for movie "John Rambo"
 Sending request to http://127.0.0.1:8081/jsonrpc from device amzn1.ask.device.AH***
 Trying to match: john rambo
 Simple match on direct comparison
 Located movie "John Rambo"
 Sending request to http://127.0.0.1:8081/jsonrpc from device amzn1.ask.device.AH***
 Sending request to http://127.0.0.1:8081/jsonrpc from device amzn1.ask.device.AH***
