### ISSUE TITLE
Chars in SLOTS, generate_custom_slots.py

### ISSUE THREAD

**Issue by danielmasur** [m0ngr31/kodi-alexa#179]
Hey guys,

I looked at amazon dev website and noticed a banner inviting me to test their fancy new skills dev website.
Clicking through it I ended up looking at the slots, specially 

Slot type values can contain alphanumeric characters, spaces, commas, apostrophes, periods, hyphens, ampersands and the @ symbol only.

This may or may not cause issues or what not. I'm certain that the "old" skills dev website didn't say anything about chars not being allowed.

EDITED

**Comment by jingai** [comment]
Thanks for the heads up.  With all of the complaints on Amazon's forums about the beta builder, I've been really afraid to enable it lol.

**Comment by jingai** [comment]
@m0ngr31 I modified the python slot generator to do this, but you'll need to do the same to the web slot generator.  I am not sure if JS regex has any nuances vs Python that I should know about, so I'm deferring it to you so I don't break it :)

**Comment by danielmasur** [comment]
You can switch back to the old interface, on doing so it reminds you that any changes you've done with the new interface will be lost.

**Comment by m0ngr31** [comment]
The HTML slot generator is to date now with those rules.

**Comment by jingai** [comment]
@ausweider let us know if both slot generators are working as expected now, if you wouldn't mind.

**Comment by danielmasur** [comment]
generate_custom_slots.py is ok,
Im not keen on trying the HTML generator without changing the password, will try this later.

**Comment by danielmasur** [comment]
all good

**Comment by danielmasur** [comment]
close sounds drastic, I'd call this Done :)
