### ISSUE TITLE
Clean video library broke

### ISSUE THREAD

**Issue by 40wattrange** [m0ngr31/kodi-alexa#18]
Now when requesting to clean the video library it triggers a "home menu" command, then updates the library, rather than just cleaning it. Im sure the updating is normal as that seems to have started before hand, but the cleaning never happens anymore.

Thanks for the updates!!!

**Comment by jingai** [comment]
The Home and Update Library commands are intended, but I'm not so sure it should Update honestly.

I'd personally expect this command to just clean the library, not update as well.

**Comment by m0ngr31** [comment]
On the clean, I'm having it do the update so that if you have a file that replaces another fike , it'll mark the new file with the same watched status before it cleans out the old one.

For some reason with the threading, it's not running the threaded command until after another command runs, so that's why I threw in the home command. I'm sure there is a work around, I just need to spend a few more minutes on it.

**Comment by 40wattrange** [comment]
It's not even displaying the cleaning dialog it normally would as it ran
through the cleaning. Now it just goes home then updates the library
without cleaning.

**Comment by m0ngr31** [comment]
Okay, I'll look into this.

**Comment by 40wattrange** [comment]
Was this fixed by chance? I havent synced since the 2.0 release, so wasnt sure if there was any reason to sync at this point.

**Comment by jingai** [comment]
Not yet, but you can check the changelog for other reasons to update.

**Comment by m0ngr31** [comment]
I submitted a PR to fix this: #68. I'll close this when it gets merged.

**Comment by jingai** [comment]
@edru, let us know when you've had a chance to test the fix in #68.

**Comment by 40wattrange** [comment]
Just updated, seems the behavior is the same. Home screen, video library updates. No cleaning dialog appears and it jumps straight to updating.

Thought that I'd add that i dont think the library can be touched at the same time. I think if its cleaning it cant update, and if its updating it cant clean. You can test this by updating your library, and as its updating try to manually mark something as (un)watched, it wont let you. Dunno if that matters with what you are doing, but remembered you stated something about it being multi threaded - so maybe its trying to do both at the same time.

If this makes a difference I am running Kodi on the latest version of Android (a Shield TV)

**Comment by 40wattrange** [comment]
- Stopped apache
- renamed kodi-alexa folder
- synced new copy from git master
- modified IP to connect properly to media center
- Started apache
- "Alexa, tell the media center to clean the video library" (saying just "library" defaults to audio now, where as it used to default to video
- No more home activity, but the updating of the library occurs immediately, and that's it. After the update, nothing further happens. Confirmed this with a new show in which a higher quality was downloaded. The older entry never removed itself after the command.
- Rebooted apache server for good measure
- Behavior still the same

So all in all "clean video library" just does a video library update, but the "home" action no longer occurs.

It was mentioned that this may be a threaded activity, not sure if you are trying to clean and update at the same time, but I know that it is not possible. KODI is a weirdo about allowing 2 things to happen w/ the library at once. (just try to do it manually and you will see it wont allow it).

Setup:
Kodi installed on NVIDIA Shield TV on Android 6.0
~6 TB of media on a virtual ubuntu server 16 (local) (OS on SSD, media all on spinning disk w/ 10 GB SSD cache)
Library is hosted on a virtual ubuntu server 16 w/ SQL (pure SSD)
All connections running over CAT5e (no wifi involved)
1 Gb WAN if it has to reach out to the web for anything

**Comment by m0ngr31** [comment]
It might be best then to just skip Updating the library first (maybe not as convient though). I'm just not sure there is a way to make it wait for the update to run and then clean consistently for every device.

**Comment by jingai** [comment]
I don't personally think it's a problem to separate them, since Kodi itself does it this way anyway.  I'm sure users are used to doing it.

**Comment by m0ngr31** [comment]
Yeah, I think you'll just have to do it in two commands @edru.

**Comment by m0ngr31** [comment]
I guess I'll leave this open until I fix the clean.

**Comment by m0ngr31** [comment]
I just commited the change to make it just clean the libraries.

**Comment by 40wattrange** [comment]
Ill test when I get home today. I dont mind two commands, I was used to doing it that way from teh beginning. Some skins even have an option to add cleaning after updating anyways.

Thanks for looking into it. Ill report back in sometime over the holiday.
