### ISSUE TITLE
Feature request: text input

### ISSUE THREAD

**Issue by mcl22** [m0ngr31/kodi-alexa#184]
I know that would be difficult to add something like "search youtube addon for {whatever}". i guess one could do that but there are so many similar addons that you'd have to select which ones to support and maintain.
But I think it would be great to have something like "write/input text {text}" for all those search windows. E.g. I open youtube addon and open the search, entering something like "science documentary 2017" is a pain if you only have the remote to enter the text.
Though I'm not sure if we get a "generic problem" here again. But perhaps you can give it a thought.

**Comment by mcl22** [comment]
I'm sorry. Just saw that it's already on the feature list :)

**Comment by jingai** [comment]
The item on the feature list is different than this --well, the text entry part is anyway.   I'll see what we can do for generic text entry.

For generic addon parsing, I think it might have to be a separate skill since the size of this is already giving us grief.

**Comment by mcl22** [comment]
Would be good to also have an option to delete the entry just for the case Alexa misunderstood and you don't have to manually delete perhaps 30 chars just to change the 1st word in your string.

**Comment by jingai** [comment]
Honestly, this should be another skill.  There's just too many opportunities for generic phrases to collide with the programmed Intents.

The method is available in Kodi-Voice, so it'd be trivial to work up another skill to do this.
