### ISSUE TITLE
Error: Failed building the interaction model.

### ISSUE THREAD

**Issue by area57** [m0ngr31/kodi-alexa#187]
Hi,

i run into the problem of saving the Skill, with the above error message, with the newest Repo version

**Comment by jingai** [comment]
I assume you are trying to use German language?

We have been having some trouble getting the utterances to work in German.  We are working on it, though.

**Comment by area57** [comment]
i tried both, german and english with the same error

**Comment by jingai** [comment]
Have you re-generated your slots to limit them to 100 items?

**Comment by area57** [comment]
For test purposes I reduced the slots on for shows, movies etc .. to one each

**Comment by jingai** [comment]
One will not be enough, but it should save.  It definitely does save here -- I have four copies of the skill deployed myself.

**Comment by jingai** [comment]
Are you using the beta builder or the 'old' builder?

**Comment by area57** [comment]
The old builder, the beta builder doesn't accept the IntentSchema.json file

**Comment by jingai** [comment]
Please try re-generating your slot items with either the web generator or generate_custom_slots.py.

**Comment by danielmasur** [comment]
Just a note: I updated my German skill to just today no trouble

Am 07.06.2017 13:57 schrieb "area57" <notifications@github.com>:

**Comment by jingai** [comment]
I've just re-generated all of my slots and updated my skill with the intents and utterances from the repository just to be sure -- it's working here too.

**Comment by jingai** [comment]
The German utterances are saving for me as well.

**Comment by area57** [comment]
ok, i dropped the Skill and build a new one, this time it wordek with the same settings in the first try.

Very strange ;-)

**Comment by jingai** [comment]
The builder definitely is weird sometimes. Glad you got it working :)
