### ISSUE TITLE
Feature request: Video skill api

### ISSUE THREAD

**Issue by jlippold** [m0ngr31/kodi-alexa#188]
This could be a game changer. 

https://developer.amazon.com/blogs/alexa/post/858c3303-eb07-4faf-a095-57436b4f8a13/amazon-enables-video-providers-to-control-content-with-the-video-skill-api-a-new-addition-to-the-alexa-skills-kitO

**Comment by jingai** [comment]
This is probably worth doing, but will require some serious thought to retain existing functionality. It is a fairly big structural change to the code. 

As well, when we get around to planning this move, we should strongly consider splitting the skill in two: a Video Skill and an Audio Skill.

**Comment by jingai** [comment]
This would be an entirely new skill.  It's on the drawing board, but I don't think it counts as a modification to this skill.
