### ISSUE TITLE
REQUEST: Read off recent additions

### ISSUE THREAD

**Issue by 40wattrange** [m0ngr31/kodi-alexa#2]
If possible, would like the ability to have Alexa read off XX number of episodes/movies/music from the recently added.

"Alexa ask kodi what episodes have been recently added"
"...what movies have been recently added"
"...what music has been recently added"

Not sure if it could gather this from the library itself or if it would need some sort of SQL integration.

**Comment by m0ngr31** [comment]
That's a good idea. I'm not sure how Kodi handles recently added music, but for TV shows and Movies, it wouldn't be that hard.

**Comment by 40wattrange** [comment]
Nice. Seems the utterances file has plenty of examples of that already in there. I actually havent installed any of this yet (doing it tonight) so not sure if it was already there or not.

**Comment by m0ngr31** [comment]
There is a command to let you know what shows you have that are new (but I think I have it cut off at 2 shows)

**Comment by 40wattrange** [comment]
Sounds good. I, personally, was only looking for 3 or 5 (or preferably definable). But glad to see its basically already there!

**Comment by 40wattrange** [comment]
After getting this working with my own home server, I have to say I really like this. It's basically exactly what I wanted.

Other requests, if possible:
Play newest episode of SHOW
Update the video/music library
Clean the video/music library

AWESOME WORK! thanks!

**Comment by m0ngr31** [comment]
Added those commands.

**Comment by 40wattrange** [comment]
Dunno if this is just the speech or a type but alexa says "lastest" instead of "latest"

EDIT: How rude of me. Thanks very much for the edits and additions. This pretty much adds what I really need!

**Comment by m0ngr31** [comment]
Yeah, that was a typo. Fixed in the latest update.
