### ISSUE TITLE
Player.Seek

### ISSUE THREAD

**Issue by jingai** [m0ngr31/kodi-alexa#20]
This should support seeking by time (e.g., +/- 5, 10, 30, 60, 600 seconds, etc) and chapters.

If possible, we could respect the user's configured seek granularity.

**Comment by digiltd** [comment]
I had a go at adding the basic stepforward, stepbackward, bigstepforward, bigstepbackward commands. I am working on being able to define a chunk of time to skip and also to jump to a specific time.
#27

**Comment by jingai** [comment]
Just commenting for myself to use [AMAZON.DURATION](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/built-in-intent-ref/slot-type-reference#duration) for [Player.Seek](http://kodi.wiki/view/JSON-RPC_API/v8#Player.Seek).  Will need to parse [ISO-8601 duration format](https://en.wikipedia.org/wiki/ISO_8601#Durations).

**Comment by jingai** [comment]
Request for opinions, too:  if I do implement arbitrary seeking ("seek 34 seconds", "seek 5 minutes", etc), do we still have a need for the pre-configured steps?

**Comment by m0ngr31** [comment]
I have the duration parser for another skill I wrote. I'll paste it into slack.

**Comment by jingai** [comment]
Thanks :)
