### ISSUE TITLE
Generating Slots

### ISSUE THREAD

**Issue by trounce1** [m0ngr31/kodi-alexa#202]
The script does not seem to pick up any movies from my video addons.

is there any way to extract them from say Specto Fork or Exodus and have them work with the commands?

Thanks

**Comment by jingai** [comment]
This skill only supports content in your library. 

Further, Exodus is a banned addon.

**Comment by trounce1** [comment]
i see ok, thank you. i was speaking in a programming sense and in theoretical terms only.
