### ISSUE TITLE
Question about streaming

### ISSUE THREAD

**Issue by nuentes** [m0ngr31/kodi-alexa#203]
To be clear: this is a question, and not an issue. This is a bit difficult to explain, so I'll do my best. I'll also add that I spent a long time considering where to post this question, and ultimately decided this was the best spot.

In my living room, I have my TV with Kodi loaded on a FireTV, as well as an Echo dot. The skill is working - everything is fine in the living room.

In my basement, I have a Raspberry Pi. It's going to be running Pi-Hole and working as a VPS. I've also installed AlexaPi on it, but since I can't access Amazon music ([source](https://github.com/alexa-pi/AlexaPi/wiki/Q&A-\(FAQ\)#does-alexapi-support-amazon-music)), I want to be able to at least play my Kodi music.

Is there any way to use kodi-alexa to stream the music loaded in my living room Kodi to the raspberry pi through Alexa? I can't think of any possible way, but I feel like there might be a better way than installing Kodi on the Raspberry Pi.

I don't want to run Kodi on the PI, as it spikes my CPU and RAM, and isn't able to be minimized in Raspbian due to a driver issue. I've been looking into ways to run Kodi as a headless application, but I'm not really coming up with anything solid. I'm really just hoping for a good idea...

**Comment by m0ngr31** [comment]
Yeah, I actually have a version of the skill that can stream music from a Kodi install. We broke it out as a seperate skill, I just haven't taken the time to document it and put it on Github. It works pretty well though. I'll try and put something together soon.

**Comment by nuentes** [comment]
Awesome - I'd really appreciate it. Glad I posted this question here, to be honest.

**Comment by nuentes** [comment]
Just wondering if there has been any progress on this. I found https://github.com/m0ngr31/kodi-music-proxy, but I think this is just a small aspect of what would be needed for this to work. Thanks!

**Comment by jingai** [comment]
All of the code was written, but I got a new job a few months ago and @m0ngr31 has some recently-acquired personal obligations that I'd guess is taking him away from things.

It basically boils down to needing to set up all of the surrounding infrastructure (mostly documentation) for a new skill.  If someone wanted to volunteer to help, I'm sure @m0ngr31 would be grateful.

**Comment by cherusker016** [comment]
Hello i tried to set it up with the streaming branch,  but no chance. Is the code outdated? Now i set up the Master Kodi Skill and use my alexas as speaker. I Switch between the different alexas with fhem and voice commands. The Problem is the Bluetooth range. If there is any new code,  where can i find it. Sorry for my bad english

**Comment by m0ngr31** [comment]
https://github.com/m0ngr31/koko
