### ISSUE TITLE
Confused?

### ISSUE THREAD

**Issue by steve55792** [m0ngr31/kodi-alexa#211]
Hi, I just bought an echo dot and ive been watching videos and videos after videos and reading articles and I was wondering is there an easier way to figure how to setup kodi with alexa. Like a step by step guide for dummys like me that having brain farts about all this. This would be an kick ass thing if i can figure this out.

                                                                                                      Thanks
                                                                                                        Steve

**Comment by jingai** [comment]
Read the [README](https://github.com/m0ngr31/kodi-alexa/blob/master/README.md) and post on the [forums](http://forum.kodi.tv/showthread.php?tid=254502) if you need assistance.
