### ISSUE TITLE
Skill response

### ISSUE THREAD

**Issue by steve55792** [m0ngr31/kodi-alexa#213]
Hi, I think i got it working but when i ask alexa to ask kodi to play a movie or show , alexa said there was a problem with requested skills response. How do i fix that?

                                                                                                        Thank you
                                                                                                         Steve

**Comment by jingai** [comment]
Github is not a support forum.  As I mentioned in the previous Issue you opened, please use the [forums](https://forum.kodi.tv/showthread.php?tid=254502) for support.

**Comment by steve55792** [comment]
oh okay oops im sorry.

**Comment by steve55792** [comment]
Not to be a smart butt but what is the Github for than?

**Comment by jingai** [comment]
The Issues here are for bugs and feature requests.  It allows us developers to track what we need to do.

The [README](https://github.com/m0ngr31/kodi-alexa) states this in the [Getting Help section](https://github.com/m0ngr31/kodi-alexa/#getting-help).

**Comment by steve55792** [comment]
oh okay thank you.
