### ISSUE TITLE
Clean up documentation

### ISSUE THREAD

**Issue by jingai** [m0ngr31/kodi-alexa#214]
1. There should be some text in the README describing how to check cloudwatch, zappa logs, heroku logs, etc, and how to provide them to us so we can help the user determine what their problem is.

2. There should be a blurb there about removing sensitive/personally identifying information.  edit: there is now a config option for this, `logsensitive`

3. There needs to be more detail provided for AWS.  Users seem to be consistently having trouble with our documentation, and tend to favor the guide over at [HowToGeek](https://www.howtogeek.com/249336/how-to-control-your-kodi-media-center-with-an-amazon-echo/).  It'd be super special if they would just provide a PR for the docs here, but that'd eat into their revenue.

4. And just so I stop forgetting about it -- we need to change out the screenshot that suggests people use the invocation name `cody` since it doesn't appear to work as well as it did before.

**Comment by jingai** [comment]
@m0ngr31 I'll add something in the docs for point 2 (unless you think the comment in the config file is enough?), but do you suppose you could handle points 1, 3, and 4?

**Comment by m0ngr31** [comment]
Is this still an issue with the [new docs](https://lexigr.am)?

**Comment by jingai** [comment]
I think points 2-4 are covered, but unless I'm missing something, it looks like point 1 is still outstanding?

**Comment by m0ngr31** [comment]
Good point. I'll get that added.

**Comment by m0ngr31** [comment]
Point 1 should be good on the new lexigr.am docs.
