### ISSUE TITLE
Request to add audiotoggledigital and 3D handling

### ISSUE THREAD

**Issue by simonrb2000** [m0ngr31/kodi-alexa#217]
Hi,

We watch a lot of 3D films and sometimes we have a surround system on and sometimes we don't. The most common commands we use are audiotoggledigital which changes the digital out put.. So we can change from pass through or not pass through.

The next is toggling the 3D on and off. I believe its either:- 

StereoMode
ToggleStereoMode

If its a massive problem then not to worry! 

Great work everyone and the support on the forum is fantastic! 
Thanks a lot :D

**Comment by jingai** [comment]
There is [GUI.SetStereoscopicMode](http://kodi.wiki/view/JSON-RPC_API/v8#GUI.SetStereoscopicMode) that we could use.

It looks like we can use [Input.ExecuteAction](http://kodi.wiki/view/JSON-RPC_API/v8#Input.ExecuteAction) with `audiotoggledigital` as the param to toggle passthrough.

**Comment by simonrb2000** [comment]
Quick work.. Once Ain jingai :D

**Comment by jingai** [comment]
Haven't actually done the work yet.. but it shouldn't be too hard.  Just need to come up with utterances that fit with the others and don't collide with existing ones.

**Comment by simonrb2000** [comment]
Brilliant. Just that your thinking about doing it means a lot. 

Set 3D mode
Toggle 3D mode
Toggle Audio Settings
Toggle Passthrough
Toggle Passthrough Audio

Just an idea and not sure if they conflict with the exiting.. Thanks again

**Comment by jingai** [comment]
Probably something like:

```
PlayerStereoscopicMode (toggle/change) (stereoscopic/three d.) mode

AudioOutput toggle (passthrough/digital) audio
AudioOutput toggle audio (passthrough/output)
```

**Comment by jingai** [comment]
All set :)

**Comment by simonrb2000** [comment]
Wicked, Thank you!!! :)

Update:- Tested audio toggle for pass through and works great :D
