### ISSUE TITLE
communicating with skill error

### ISSUE THREAD

**Issue by wbrady11** [m0ngr31/kodi-alexa#233]
Hello m0ngr31, ive installed this code via the Paulhibbert tutorial on youtube, some things look a bit different when you get into AWS but i think all has been done right, your work looks great and im itching to try it out but when i ask alexa dot to play something i get "There was a problem connecting to the requested skill" on the alexa app, the dot itself just turns blue and stays like that until i say stop, im sure you get asked a thousand times but do you have any idea what ive done wrong to cause this error? im new to this game so any help would be very much appreciated and it does look great :)
Thanks

**Comment by m0ngr31** [comment]
Run `zappa tail` and see what it says

**Comment by wbrady11** [comment]
Sorry Joe i have looked on google and dont even know where to start with installing zappa never mind using it, i will keep looking and thanks for the reply

**Comment by m0ngr31** [comment]
Ahh okay, I'm unfamiliar with Paul Hibbert's tutorial. Can you link it for me?

**Comment by wbrady11** [comment]
No problem mate, its here i hope....it looks like you changed your code since it was made as mentioned on the read up but people say it still worked....https://youtu.be/_KSlz_lT1k4

**Comment by wbrady11** [comment]
I wiped all the stuff i did previous to this post and installed it again...it worked 👍
Thanks again for the reply and looking forward to having a mess around..
