### ISSUE TITLE
Canadian Language Support

### ISSUE THREAD

**Issue by Xtropy74** [m0ngr31/kodi-alexa#237]
Now that the Echo is released in Canada, I changed the language from "English (United States)" to "English (Canada)" and kodi-alexa stopped working. Changing it back to "English (United States)" fixes the issue. Can the "English (Canada)" language be supported?

Thank you

**Comment by m0ngr31** [comment]
As an easy fix, you can just setup the skill as English (Canada) instead of US and it should work fine.
