### ISSUE TITLE
Calls timing out?

### ISSUE THREAD

**Issue by karl0ss** [m0ngr31/kodi-alexa#238]
Wonder if someone can help me.

I have this all setup, and am using the s3 bucket cache, but certain calls fail....

I can ask the following and the commands work fine,

- Play a random episode of X
- Play the latest episode of X
- if there are any episodes of X
- do i have new films
- play season {Season} episode {Episode} of {Show}

But calls like
- are there new shows
- what new shows do i have to watch

Timeout and fail, and give this response via the skill tester 
`The remote endpoint could not be called, or the response it returned was invalid.`

I can't work out what needs to be done to get these to work as it seems to be working for the most part

**Comment by jingai** [comment]
There was a typo in the code for the name of this handler.  I've updated it -- let me know if that resolves your issue.

**Comment by karl0ss** [comment]
I have done the git pull and zappa update/upgrade, but still getting this via the simulator, im not at home, but I believe echo will still fail.

`The remote endpoint could not be called, or the response it returned was invalid.`

**Comment by karl0ss** [comment]
is there anything i can get you from zappa tail dev to help with the issue? I can't see anything obvious in there....

**Comment by jingai** [comment]
Yes, we would need the log to help further -- it is definitely working here.

**Comment by jingai** [comment]
Please post on the forum if you have further issues.  It's likely simply the way you're asking -- if we need to add additional utterances, we can, but let's figure it out on the forum.
