### ISSUE TITLE
Service error 500

### ISSUE THREAD

**Issue by sahara101** [m0ngr31/kodi-alexa#242]
Hi,

I managed to set up the skill, also working. I have two shows that are not working and I am receiving above error. One is the flash and the other one is gantz (Alexa does not really understand gantz, I tried to add G. A. N. T. Z. to the slot) but with same error. Why is this? Ty!

**Comment by m0ngr31** [comment]
I can't do anything without the logs

**Comment by sahara101** [comment]
Sorry. Is this what you need?

https://pastebin.com/xJEF1L9r

**Comment by digiltd** [comment]
@sahara101 I have "the flash" working fine, would you mind moving this question to the kodi forum and we can chat about it there?

https://forum.kodi.tv/showthread.php?tid=254502

**Comment by jingai** [comment]
Being handled on the forums.
