### ISSUE TITLE
connection problem to aws

### ISSUE THREAD

**Issue by toptechnology2010** [m0ngr31/kodi-alexa#243]
On amazon service simulator i get the error:

The remote endpoint could not be called, or the response it returned was invalid.

The alexa app it say's:

unable to connect to host.

Request indentifier: amzn1.echo-api.request.0f050525-47d2-4d11-92ff-96a9507a7bea

a connection could not be established to recource? [https://xxxxxxxxxx.execute-api.us-east-1.amazonaws.com/dev]. Type [HTTP], Region [DEFAULT]

Can you help me? or point me in the right direction?
thx, Marcel

**Comment by jingai** [comment]
Please post on the forum for support questions.

**Comment by toptechnology2010** [comment]
where is that?

**Comment by jingai** [comment]
Read the Getting Help section in the README.

**Comment by toptechnology2010** [comment]
thx. much help. could have pointed me
