### ISSUE TITLE
kodi-alexa

### ISSUE THREAD

**Issue by jdzmfg** [m0ngr31/kodi-alexa#244]
Currently I have the amazon echo 2nd generation and the fire stick tv in the US but As said, "Unfortunately, as of this moment, we cannot simply ship this skill normally as other skills on Amazon's skill marketplace. The main technical hurdle is that some features we would need are currently only supported in the US region."

I guess i will wait until you guys can put this on the skill marketplace because it is daunting to try to put this together by myself, its sad that i rather wait but if it was easier to put together i would, not sure if you guys have a twitter but i would like to keep up with this project

**Comment by jingai** [comment]
We post regularly to the forum.

**Comment by jdzmfg** [comment]
link ?

**Comment by jingai** [comment]
https://github.com/m0ngr31/kodi-alexa#getting-help
