### ISSUE TITLE
Suggestion Update Readme for non standard https ports

### ISSUE THREAD

**Issue by vajonam** [m0ngr31/kodi-alexa#250]
While doing this for the very first time I stubmed on the fact that alex wont work on non-standard https ports.

Finally found this, would be obvious to anyone who and done this before, but not for a first time user. 

https://stackoverflow.com/questions/34369780/does-alexa-skill-kit-listen-on-other-port-of-ssl-besides-443

> The Alexa service is strict regarding app endpoints. It will only call out using HTTPS on port 443 whether it's calling an app during development or deployed to production.

https://developer.amazon.com/docs/custom-skills/host-a-custom-skill-as-a-web-service.html

> The service must accept requests on port 443.

**Comment by jingai** [comment]
Feel free to submit a PR updating the documentation.
