### ISSUE TITLE
Can't get the Alexa App to find skill

### ISSUE THREAD

**Issue by rdnuss001** [m0ngr31/kodi-alexa#253]
Hi,
I'm new to all of this, and I don't know what i'm doing wrong.  It appears that I have everything set up with green checkmarks on everything, and my lambda management seems to be triggering, so i'm not sure why I can see the skill on my app.  Without that, I can't get my echo to recognize the skill.  Thanks for setting all of this up, I hate how hard kodi is to use for my friends and gf.

**Comment by jingai** [comment]
Please use the forum for support requests.
