### ISSUE TITLE
New skills kit environment.

### ISSUE THREAD

**Issue by ravi09x** [m0ngr31/kodi-alexa#259]
Hi,
Looks like amazon has updated their alexa skills kit environment. In the new environment there is no option to copy and paste multiple utterances and intents. 

Is this right or i am not able to find the right area? Is there a workaround?

**Comment by m0ngr31** [comment]
Yes, they changed it. New solution is imminent.

**Comment by yesnomaybeyes** [comment]
Hi @m0ngr31,

I have a JSON file from the console of the entire skill I setup for myself for kodi-alexa. You're now able to just paste in the JSON blob and Amazon will read that and add everything into the GUI, all that's left after that is a save model and build model.

If you want I can upload it somewhere, with all the slot type values set to "Empty".

It was a mix of manual effort and a tiny script to mass-insert JSON objects.

**Comment by denbue** [comment]
Hi @Xorkle ,

would you mind sharing your JSON blob or even the generator itself?

**Comment by m0ngr31** [comment]
@denbue Sorry, forgot to post this last week: https://github.com/m0ngr31/lexigram-cli

Docs are at https://lexigr.am
