### ISSUE TITLE
pip install -r requirements.txt

### ISSUE THREAD

**Issue by mentex23** [m0ngr31/kodi-alexa#262]
Hello,

very cool project! thank you.
I followed your guide an if i try to install:

pip install -r requirements.txt

i receive an error:

(venv) C:\Users\mentex\Desktop\kodi-alexa\kanzi-master>pip install flask-ask
Collecting flask-ask
  Using cached https://files.pythonhosted.org/packages/6a/f5/d4709ae94584a0b1541e9b52b2d25a8a1bdb6e2da9d6870f23fdd0523a30/Flask-Ask-0.9.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\mentex\appdata\local\temp\pip-install-zjxmxi\flask-ask\setup.py", line 8, in <module>
        from pip.req import parse_requirements
    ImportError: No module named req

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\mentex\appdata\local\temp\pip-install-zjxmxi\flask-ask\

how can i fix this?

**Comment by m0ngr31** [comment]
It's due to a compatibility issue with the way the Flask-Ask package is installing packages and the pip version on your computer.

I have a PR in to fix the issue on Flask-Ask, but until that is merged in, you'll have to use a pip version < 10.

**Comment by reeso3000** [comment]
Mentex23 -  I had the same issue and was running pip 9.01 (so I thought) - pip was 9.0.1 when running from the python directory but was running version 10 from within the virtual enviroment (venv). Just run the following command (if using windows) after the activate.bat command

"c:\users\\*user*\kanzi\venv\scripts\python.exe -m pip install pip==9.0.1"

*user* - your user name.


It should uninstall version 10 and install 9.01 so you can finish the install :D

**Comment by mentex23** [comment]
Great!!! Thank you for your unbelievable fast help!!
