### ISSUE TITLE
Alexa Skill Page

### ISSUE THREAD

**Issue by mentex23** [m0ngr31/kodi-alexa#263]
Hello,

it is me again:-)
I looks like the Skill dev page has changed.
If I try to enter the slot values, i get the error e.g. for MOVIES:

Slot value length exceeds the limit of 140 characters.

Also issue with the IntentSchema.json limit 800 characters

**Comment by mentex23** [comment]
this time no help?

**Comment by m0ngr31** [comment]
Are you using the [new cli](https://lexigr.am)? It solves those issues for you.

**Comment by mentex23** [comment]
thanks.. this solves the issue..
