### ISSUE TITLE
Amazon login page goes in timeout

### ISSUE THREAD

**Issue by weha** [m0ngr31/kodi-alexa#265]
After poking around a bit it finally launched (having to disable service as well because port 9090 seems to be hardcoded) I accessed the webpage but it just keeps loading while saying: Switch to 'Login with Amazon' page...
After a while I get "connection refused"

Also, there's an error in the manual where it says N to continue instead of stopping but it is now Y apparently.

**Comment by m0ngr31** [comment]
Try `lexigram login --no-browser true`

**Comment by weha** [comment]
Ok, one step further.
Now I get this vague message:
 lexigram init-skill kanzi
 ✖ Initialize kanzi skill
   → Could not create skill. Please try again.

Retrying gives the same message of course.
Since there is no error, I don't know what to do next. :(
Does it require a file? Where is the auth code saved from the login command?

**Comment by m0ngr31** [comment]
What OS are you running this on?

**Comment by weha** [comment]
Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-119-generic x86_64)

**Comment by m0ngr31** [comment]
Auth code is saved in `~/.ask`.

Try this:
``` bash
npm install -g ask-cli@1.1.2
ask new -n kanzi
```

See if that gives you an error

**Comment by weha** [comment]
ask new -n kanzi
[Error]: Cannot resolve profile [default]

**Comment by m0ngr31** [comment]
Yeah, sounds like it doesn't like your login. Do you know what's causing a conflict on that port when it tries the regular login?

Also, it'd be better if you post this on the [Kodi forum](https://forum.kodi.tv/showthread.php?tid=254502) so everyone else can see the same issue. Or you can email me (address is in my Github profile)

**Comment by m0ngr31** [comment]
Or did you not use the default profile when you logged in without the browser?

**Comment by weha** [comment]
Strange, the manual URL seemed to have worked fine.
Yes, a Gitlab service. 

Well the forum is abit chaotic to follow up on a single issue is it not?

I moved the cli_config file and started over and now it works.
As it turns out I was indeed not using the default profile but one that was created before named Kanzi.
Don't remember how this happened, I do remember lexigram asking me a profile name at some point.
And of course, kept on using this profile.

lexigram init-skill kanzi
 ✔ Initialize kanzi skill

Should I not see the Kanzi skill in my skills list now on Amazon?
It's all a bit vague to me what the init skill actually does.

**Comment by m0ngr31** [comment]
Forum works pretty well.

The init command will only create the folder and keep information about the skill. It won't show up in Amazon until you've run the deploy command.

**Comment by m0ngr31** [comment]
Support conversation being carried over email since this isn't a code related issue.
