### ISSUE TITLE
File I need to translate for French

### ISSUE THREAD

**Issue by G-Dracarys** [m0ngr31/kodi-alexa#266]
Hi, Amazon Echo will be released in France on 13/06/18, and I really want this feature for my kodi, could you please tell me which files I need to translate ?

Thanks.

**Comment by jean-gui** [comment]
I believe that would be https://github.com/m0ngr31/kanzi/blob/master/speech_assets/SampleUtterances.en.txt

I'm also interested in that translation. Please submit a PR if you do translate it so others can benefit from it.

**Comment by Brownie2002** [comment]
If you need PR, I can do it also. I am French and I want to use Alexa with kodi. Just let me some hints in order to do a good PR.

**Comment by jean-gui** [comment]
I've just opened a couple PRs for the French version.
