### ISSUE TITLE
No pause or stop command?

### ISSUE THREAD

**Issue by bisca330** [m0ngr31/kodi-alexa#269]
Hello,

I realize that there is no voice command to pause or stop a media. Is it an oversight ? And why else this choice?

Regards,

Micky

**Comment by jingai** [comment]
There are:  the skill makes use of Alexa's built-in Intent library for these, so they are not listed explicitly in the language files.

In English, things like `Alexa, ask Kodi to stop` or `Alexa, ask Kodi to pause` work fine.

**Comment by bisca330** [comment]
OK. Thank you very much for your answer.

Micky

**Comment by jingai** [comment]
Also, it'd be better if you used our [forum](https://forum.kodi.tv/showthread.php?tid=254502) for questions like these rather than creating a new Issue here.  If after asking on the forum you don't get a satisfactory response, feel free to raise it as an Issue here.

**Comment by bisca330** [comment]
Very well, I'll do that in the future.

Micky
