### ISSUE TITLE
botocore.exceptions.ClientError

### ISSUE THREAD

**Issue by balaprasad18** [m0ngr31/kodi-alexa#270]
hello everyone, i need to cross check the atendance for the employee based on changing the date forward and back, but i am facing the same issue. Is it possible or not?? My assumption is when i checks in my system takes local time and date what i changed (eg: 3 days before from today), AWS will take current date and time. How to resolve this ???

botocore.exceptions.ClientError: An error occurred (InvalidSignatureException) when calling the CompareFaces operation: Signature expired: 20180707T233021Z is now earlier than 20180710T071214Z (20180710T071714Z - 5 min.)

**Comment by jingai** [comment]
Pretty sure you're in the wrong place, bud.
