### ISSUE TITLE
Youtube Integration

### ISSUE THREAD

**Issue by vijaykirann** [m0ngr31/kodi-alexa#271]
Please add youtube integration.
e.x: Play "abc" on youtube.
That would be very helpful..

And ofcourse the skill is absolutely rocking.

**Comment by jingai** [comment]
The big problem here is recognizing what you want to play on YouTube.  We can get good matches for items in your library because the skill can see the library.  For YouTube -- and any other plugins -- we cannot.

**Comment by vijaykirann** [comment]
Thanks for explaining.the reason I requested was coz it was present in other skill ..all it does it runs the query and  plays the first search result that is more likely to be the video that user is looking for..
Thanks for looking into it though..much appreciate it.
