### ISSUE TITLE
Zip file too big for AWS Lambda

### ISSUE THREAD

**Issue by bisca330** [m0ngr31/kodi-alexa#273]
Hello,

I'm trying to install Kanzi (in French version) and I'm having a problem importing the zip file into AWS Lambda. Indeed, the upload is not done and AWS Lambda tells me that the zip file is too big. The latter is 8.4 MB whereas normally AWS Lambda accepts files up to 10 MB.
However, it's noted in AWS Lambda that you can use S3 for large files, but unfortunately I do not know how to do it.
Would anyone know how? Either by finding a way to reduce the zip file, or by giving a procedure to use S3.

I thank you in advance for the help you will give me and I apologize if my English translation is too approximate.

Regards,

Micky

**Comment by m0ngr31** [comment]
What's the exact message that it shows? 8.4MB should be perfectly fine. It does say something about it being too big to edit once it's uploaded though.

**Comment by bisca330** [comment]
Thank you for your quick reply.

Yes indeed, 8.4Mo seems ok, but AWS Lambda does not handle it. The exact message is attached, in French :

![kanzi error](https://user-images.githubusercontent.com/32873895/44423035-3ef0c500-a585-11e8-9a42-cc1488befedf.jpg)

In English it means: "The deployment package of your Lambda function" kanzi "is too large to enable inline code editing, but you can still invoke your function right now." Maybe it's just a warning and I can still deploy Kanzi?

Micky

**Comment by m0ngr31** [comment]
That message is perfectly normal. It just means that it's not editable by hand and you have to upload a new zip file to modify anything. You can go forward with your deployment.

**Comment by bisca330** [comment]
OK, thank you. I will try the deployment.

Regards.

Micky

**Comment by bisca330** [comment]
Hello,

I managed to deploy, but Alexa gives me an error when I invoke the skill:
![erreur appel skill kanzi](https://user-images.githubusercontent.com/32873895/44448474-a93c5080-a5eb-11e8-9a12-a07af1d2e836.jpg)

But I think I know why, I did not get the latest version of the kodi.conf file and I installed in English:

```
# Currently supported languages: en, de, fr
language = en
```

So this morning by testing I ask Alexa in French to do some actions on Kodi and I got the error above.

I will test tonight by speaking in English to Alexa and if it's OK I will start my installation again but in French.

Micky

**Comment by jingai** [comment]
The skill needs to be deployed for the same region your Echo is configured for.

**Comment by bisca330** [comment]
Hello,

I managed to deploy Kanzi in French, and it works. 👍  I did some tests and I already noticed things that could be improved.

1) I noticed that Alexa is listening only a few seconds when we say "Alexa ask kodi ...". So I wonder if we can change the call word to the skill and make sure that Kodi stays active until we say another command so that kodi does not listen anymore?
For example :
"Alexa, activate Kodi" -> for kodi to start listening without calling Alexa at each order.
"Thank you Kodi" -> for kodi to stop listening.
Of course when we start a media Kodi will automatically stop listening.

2) I use Kodi's Aeon Nox skin and set up my menu banner with items like "Movies" for all movies, "Kids" for cartoons, "Anime" for mangas that are a bit violent for children or "Shows". With the skill Kanzi we can go to the menu ("Alexa ask Kodi home") and we can walk on the menu banner ("Alexa ask Kodi right", "left" ...) but I did not find any word in the skill to enter these items. Even when I'm in my movies list I can not start reading. Could we create a simple word like "OK", "Enter", "Go" or "going inside" that would simulate the click of the mouse or the key entry of the keyboard?

3) Most of the time I do not know what movie I'm going to watch, so I go to the "Movies" item of my menu banner and I have the list of all my movies that is displayed, but I have about 900 movies. When I use my remote for Kodi I can scroll through the list very quickly. But can we do it with the skill? I have not found. Maybe with the words "scroll down/up the list" and "stop" to stop scrolling. Is it possible ?

4) I have the impression that it is difficult for Alexa to recognize the name of an english movie correctly pronounced in english when the skill is installed in french. I tried for example "A history of violence" and I did not manage to launch it. But no problem for simple titles like "Taken" or french movies titles. Is there any learning to be done to Alexa to improve the experience?

These are my first remarks, maybe there will be others but anyway thank you very much for the work done on this skill.

Regards,

Micky

**Comment by jingai** [comment]
1. We do keep the session open (at least for as long as Amazon allows), but not for all Intents.  Basically, any Intent that would start playback of media, the session is immediately closed;  most other Intents will open the session again and Amazon will time it out after 10 seconds.

2. The _View*_ Intents do this.  For example:
```
affiche les films
cherche des films d' {MovieGenre}
cherche des films de {MovieGenre}
montre des films d' {MovieGenre}
montre des films de {MovieGenre}
montre les films
ouvre les films
recherche des films d' {MovieGenre}
recherche des films de {MovieGenre}
va aux films
``` 

3. The _PageUp_ and _PageDown_ Intents handle this.  For example:
```
suivante
montre plus
``` 

4. Unfortunately, what Amazon passes to the skill is what we have to work with.  German users had similar issues to this in the beginning, but it got better with time.

For general questions like these, please use [the forum](https://forum.kodi.tv/showthread.php?tid=254502).

**Comment by bisca330** [comment]
Thank you and sorry for posting this message here. I'm going to transcribe it on the Kodi forum to continue to discuss my questions.

Micky
