### ISSUE TITLE
A couple of command suggestions

### ISSUE THREAD

**Issue by mlipmanx** [m0ngr31/kodi-alexa#274]
Would be nice if there were some commands to control live TV, eg:
Show TV Guide
Switch to channel 7
show live TV

**Comment by jingai** [comment]
It's already been previously decided that PVR/plugin support should be its own skill.  There's just too much overlap in commands.

Anyone is free to fork this and utilize https://github.com/m0ngr31/kodi-voice to write such a skill.  I don't personally have a PVR nor do I utilize streaming video addons, so I just don't have much incentive (nor time) to do it myself.  @m0ngr31 may pick it up at some point, but he's been pretty busy lately too, and I don't think he has too much personal interest in it either.
