### ISSUE TITLE
Files i need to translate for Spanish

### ISSUE THREAD

**Issue by elopezmadrid** [m0ngr31/kodi-alexa#275]
which files i need to edit?

**Comment by avogabo** [comment]
+1. Help please

**Comment by jingai** [comment]
sample_slotvals.es.txt
templates.es.yaml
utterances.es.txt (and convert to speech_assets/SampleUtterances.es.txt)

**Comment by ruben0909** [comment]
@jingai Could you review this PR 
https://github.com/m0ngr31/kanzi/pull/276
and this
https://github.com/m0ngr31/lexigram-cli/pull/4
Thank you in advance
