### ISSUE TITLE
Kodi Voice integration w/o Alexa

### ISSUE THREAD

**Issue by SweeneyToddTheDemonBarber** [m0ngr31/kodi-alexa#3]
Hey m0ng31,

I really like your program. First of all I have to tell you I'm kinda noobish. I currently have a HT set-top box with openelec (Kodi), a Raspberry Pi running a voice command program (like Alexa) called PiAUISuite by Steven Hickson. I'm using SSH to successfully send commands from the Pi to Kodi, however I would like to use your program to send them. In PiAUISuite I have the command:

Kodi ==curl --data-binary '{ "jsonrpc": "2.0", "method": "VideoLibrary.Scan", "id": "mybash"}' -H 'content-type: application/json;' http://192.168.15.141:90/jsonrpc 

where the left side is what I say and the right the command.

I would like to know if there's a way to modify your program in order for me to write it in the command line followed by the command I said (play, pause, etc.)

Thanks

**Comment by m0ngr31** [comment]
I'm not sure my program would be able to handle the requests the same way that PiUISuite does. It looks like something I'd have to write from the ground up with that in mind.
