### ISSUE TITLE
SetShuffle/SetRepeat commands

### ISSUE THREAD

**Issue by jingai** [m0ngr31/kodi-alexa#31]
We'll need to think about SetShuffle a bit, and by extension, SetRepeat.  We already have:
- shuffle all music
- shuffle (/music by/artist) {Artist}
- shuffle playlist {Playlist}

An invocation that isn't either confusing or overlapping the above might be difficult to think of..

So, options would be one of:
1. don't add SetShuffle/SetRepeat,
2. alter the invocation of the existing shuffle commands,
3. think of something that makes sense and coexists in the current schema.

I'm kind of leaning toward 1, since if it ends up even a little bit confusing, it ends up being a command users avoid altogether.

**Comment by jingai** [comment]
@m0ngr31, I'll defer to your opinion on this one.  It seems like it would end up confusing enough that I'd never use it, so if you or anyone else feels strongly about it one way or another, feel free to do whatever.

**Comment by m0ngr31** [comment]
Yeah, it seems like there is already some confusion on the commands. We might revisit this if there is some demand for it.
