### ISSUE TITLE
Reverse order of operations when cleaning library & timeout time

### ISSUE THREAD

**Issue by 40wattrange** [m0ngr31/kodi-alexa#4]
(I'll preface this by saying I am now running a MySQL backend, vs a local library, so this could very well be the reasoning behind this)

So I noticed that whenever you want to clean the library, it will also update it afterwards. Was wondering that if you keep them paired that you could possibly reverse the order?

I only ask because if something has updated the quality of a video and replaced it with one that technically has a different file name, that you lose your "played" status. Basically this is because the file entry is removed, then added on the update. If it triggered the update first, it would catch this and keep the played status, then when cleaning remove the old entry, but keep the status. This happens a lot with me as I have Sonarr and Couchpotato actively updating qualities when they become available. Due to this, everything starts showing up as unwatched.

Also, is there a way to modify it's response time when cleaning? 80% of the time my library is still running through a cleaning when the echo decides to stop waiting and trigger a "skill failed to respond" error, though its actually working.

**Comment by m0ngr31** [comment]
The way to do this would be to fire off the call asynchronously, but I'd have to look into doing that in Python 2.7. It'd solve all of these "skills failed to respond" issues.

**Comment by m0ngr31** [comment]
My update tonight should resolve these issues.
