### ISSUE TITLE
New shows not detected

### ISSUE THREAD

**Issue by A69Tor** [m0ngr31/kodi-alexa#40]
After adding a new show to my library the skill can not find it.  Says no show with that name found in spite of it listing the show in the WhatNewShows check.

**Comment by jingai** [comment]
Have you tried adding the show to the SHOWS slot?

**Comment by A69Tor** [comment]
As a solution, yes I did.  But that is not how the slot values are intended to work. They are a list of weighted values, not a definitive list.  And with new shows coming out all the time, having to manually add them all to the slots would be ridiculous.

That being said, it looks like it may actually have to do with the new show having a number in the name, "Channel Zero" and instead the skill was looking for "Channel 0" in spite of the Alexa log showing it correctly.

**Comment by jingai** [comment]
Yes, I realize how they're supposed to work; I was just wondering if it made it work for you if you added it.

I'll close this then since #39 addresses your other issue.
