### ISSUE TITLE
Validation fails on AWS Lambda

### ISSUE THREAD

**Issue by digiltd** [m0ngr31/kodi-alexa#41]
The validation fails when using the latest master branch.

```
Verifying application ID...
global name 'verifier' is not defined: NameError
Traceback (most recent call last):
File "/var/task/wsgi.py", line 1289, in lambda_handler
verify_appid(appid)
File "/var/task/wsgi.py", line 1272, in verify_appid
except verifier.VerificationError as e:
NameError: global name 'verifier' is not defined
```

As a quick fix I replaced:

``` python
  # Verify the application ID is what the user expects
  verify_appid(appid)
```

with

``` python
  # Verify the application ID is what the user expects
  if (event['session']['application']['applicationId'] != env('SKILL_APPID') ):
      raise ValueError("Invalid Application ID")
```

This validates the appid without too much fuss.

An advantage of the app being hosted on AWS Lambda is cert verification is not needed. 

From the docs ([source](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/developing-an-alexa-skill-as-a-lambda-function#about-lambda-functions-and-custom-skills)) :

> You do not need to verify that requests are coming from the Alexa service yourself. Access to execute your function is controlled by permissions within AWS instead. 

I know we have discussed this briefly before (#32) about how it adds a lot of extra weight to the package (10mb).  It also adds a bit more complication to the setup. Using `lambda-deploy deploy` to deploy will only install the dependencies listed in `requirements.txt`. When testing my PIP couldn't find `OpenSSL`, not sure if this is a platform thing (macOS here) but when I replaced it with `pyopenssl` it was able to install allllll the packages it required.

**Comment by jingai** [comment]
Are you saying it fails even if you install the dependencies?  The title of the Issue doesn't seem to match your description.  If you install the dependencies, importing verifier.py should work.

Now, I realize you're trying to get verification of the appid to work without installing the crypto dependencies. I can break that bit out of verifier.py if that's what you're asking for.

Thanks for the confirmation that AWS Lamba performs cert validation outside of the skill.  I'll remove the options for the Lambda handler for cert verification.

**Comment by digiltd** [comment]
Sorry if I wasn't clear. 

Initially I added `aniso8601, six, pyOpenSSL` to my requirements file so Lambda would install them as part of the deployment. It also uploaded the `verifier.py` file along with `kodi.py` and `wsgi.py` files. I also modified the .env to include the new variables. I had to re apply the changes I have made previously to allow for the https connection to my local network, but other than that it was  setup using the new files. When I tried to send a command using the skill it was failing and giving me the error I posted above.

The rest of the post was to show the changes I made to get just the appid bit working. I have edited the original post as I can see that me showing the appid error was not relevant.

**Comment by jingai** [comment]
Pull

```
import aniso8601
import verifier
```

out of the try clause and see what it's complaining about.  I am guessing it's not able to find a dependency.

**Comment by digiltd** [comment]
Tried pulling them out of the try, but alas:

_Unable to import module 'wsgi': /var/task/cryptography/hazmat/bindings/_openssl.so: invalid ELF header_

It is not something I am familiar so can't really offer any more help other than reporting back with the error logs.  Perhaps a version conflict due to using pyopenssl rather than OpenSSL?

But do you think it is worth trying to get working on AWS when there isn't a need for it on AWS?

**Comment by jingai** [comment]
No, it's not worth getting working, but the data point is useful if someone has a similar issue with the wsgi handler later on :)

I already have a patch to pull the appid verification out of verifier.py, but I'm not home yet so I can't test until later.

**Comment by jingai** [comment]
1e1de9c87c7e90aca68fca8517ec9f0e40e9f7bb and 0e31223f64d0f7f82e8e7a90302fdb33c7942d31 should address this.  Let me know if not.

**Comment by jingai** [comment]
@digiltd , things ok for you now?

**Comment by digiltd** [comment]
Things have been fine since my initial removal of the verifier bits and replacing the appid verification with:

```
  # Verify the application ID is what the user expects
  if (event['session']['application']['applicationId'] != env('SKILL_APPID') ):
      raise ValueError("Invalid Application ID")
```

 I haven't tested the current version from a new user's perspective, will try tomorrow.

**Comment by digiltd** [comment]
Tested with a fresh pull of master using the basic requirements.txt (plus a small edit to get it working with my proxy url) and it worked as I expected when I asked "are there any new episodes of ..." 

You might want to remove `SKILL_VERIFY_CERT` leftover in `LAMBDA_ENV_VARS`

ta

**Comment by jingai** [comment]
I did remove it with 1e1de9c87c7e90aca68fca8517ec9f0e40e9f7bb

edit: Ahh.. doing too many things at once.  Removed it in c7367ba466b00ffc9b5ec12e21f719853c7edaac

**Comment by jingai** [comment]
Calling this one done now then.  Thanks for the help testing @digiltd !
