### ISSUE TITLE
Sending request to 127.0.0.1:8080

### ISSUE THREAD

**Issue by matty87a** [m0ngr31/kodi-alexa#48]
have set all variables in .env but each time i test the intent it fails.

looking in the function logs within AWS  - it picks up the intent but then forwards it to local host:

Requested intent: CurrentPlayItemInquiry
Currently playing item
Sending request to 127.0.0.1:8080
END RequestId: 7211f463-9b8a-11e6-8032-e7dd52ef232c

Has anybody else seen this?

Have created a new .env file and re-deployed but the issue persists

**Comment by jingai** [comment]
127.0.0.1:8080 is the default if the environment variables aren't set.  So, for some reason, your .env file isn't picked up.

FYI, you'll have better chance at support if you post at http://forum.kodi.tv/showthread.php?tid=254502

**Comment by Xaelias** [comment]
Hmm. I set it up myself 2 days ago (I was running an old version). Created the .env file, setup the variables in there. Worked like a charm.

**Comment by matty87a** [comment]
Issue seems to be its skipping the .env file completely:

2016-10-26 15:08:35:WARNING:lambda_deploy: Skipping inclusion of of .env file - use LAMBDA_ENV_VARS instead (see documentation for more information)

**Comment by matty87a** [comment]
the LAMBDA_ENV_VARS line had missing data - my bad!
