### ISSUE TITLE
deploy-to-lamda.py invalid syntax

### ISSUE THREAD

**Issue by jimdineen** [m0ngr31/kodi-alexa#51]
I am completely new to this so forgive me if this is obvious but trying to run the set up for AWS when I run the command "python deploy-to-lambda.py" I get invalid syntax on line 34.

Any idea what I am doing wrong?

**Comment by digiltd** [comment]
Have you installed `lambda-deploy` ?

**Comment by jimdineen** [comment]
I have I think, could it be where it is installed?

**Comment by digiltd** [comment]
what does `where lambda-deploy` return?

**Comment by jimdineen** [comment]
c:\kodi-alexa>where lamda-deploy
INFO: Could not find files for the given pattern(s).

**Comment by digiltd** [comment]
there is a typo in the last command

also, check you can run `lambda-deploy` from the command line (make a new folder and cd into it)

... ah, windows. I will check

**Comment by jimdineen** [comment]
Sorry I am an ass:

c:\kodi-alexa>where lambda-deploy
C:\Python\Scripts\lambda-deploy.exe

I can run it but it returns:

c:\kodi-alexa>lambda-deploy
Traceback (most recent call last):
  File "C:\Python\Scripts\lambda-deploy-script.py", line 11, in <module>
    load_entry_point('lambda-deploy==0.1.2', 'console_scripts', 'lambda-deploy')()
  File "c:\python\lib\site-packages\pkg_resources__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python\lib\site-packages\pkg_resources__init__.py", line 2608, in load_entry_point
    return ep.load()
  File "c:\python\lib\site-packages\pkg_resources__init__.py", line 2268, in load
    return self.resolve()
  File "c:\python\lib\site-packages\pkg_resources__init__.py", line 2274, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "c:\python\lib\site-packages\lambda_deploy\lambda_deploy.py", line 119
    envinfo.external_attr = 0644 << 16L
                               ^

Many thanks for your time BTW!

**Comment by digiltd** [comment]
What version of python are you using?

`python --version` is what I would use on a unix machine, not sure it is the same.

and check pip is installed and the version

`pip --version`

**Comment by jimdineen** [comment]
python --version
Python 3.5.2

> pip --version
> pip 8.1.2 from c:\python\lib\site-packages (python 3.5)

I thought trying this on a windows machine would be a pain!

**Comment by digiltd** [comment]
ah, Python 3 might be the problem. Whilst it is the latest, 2.7 is still the most widely used and supported version. AWS Lambda only supports 2.7.

Do you have python 2.7 installed as well?

try

`python2 --version`

and 

`pip2 --version`

**Comment by jimdineen** [comment]
Aha. I do not. WIll try that and get back to you! Many thanks.

**Comment by Xaelias** [comment]
Yeah lambda-deploy does not play nice with python3. Which made realize that for some reason on my Mac I had python 2 and 3, but only pip3 /shrug

**Comment by jimdineen** [comment]
Jackpot. That worked. Is it worth mentioning the Python 2.7 requirement in the instructions (though given I am a newbie I wouldn't put it past me to have missed it!

**Comment by jingai** [comment]
It might be, though I believe Amazon mentions it already in their own documentation for Lambda.

**Comment by digiltd** [comment]
> though given I am a newbie I wouldn't put it past me to have missed it!

oops

https://github.com/m0ngr31/kodi-alexa/blob/master/README.md#aws-lambda
