### ISSUE TITLE
Multiple Instances of Kodi

### ISSUE THREAD

**Issue by jimdineen** [m0ngr31/kodi-alexa#52]
Many thanks for your previous help previously, all not up and running on one device.

I have kodi set up in a second room. Is there an easy way to set up two instances? I can set up another skill with a different invocation name but I assume it would have to refer to a different instance of kodi-alexa on lambda with different port/login details etc. The bit I cannot work out is how to change the name of the function in the deploy stage so that is newname-alexa not kodi-alexa. 

I suspect this may be simple but as said before I am very new to this!

Thanks in advance.

**Comment by digiltd** [comment]
At the moment you are correct. You would have to set up a separate Skill Kit which points to a separate AWS Lambda. Basically repeating the whole process including slot generation.

I would keep two folders on your local machine with the two different env files.

The bit you need to change is in the file:

`deploy-to-lambda.py`

line 14:

`app_name = "kodi-alexa"`

Just remember that your changes will be overwritten when you next pull/download any updates from this repo.

**Comment by jingai** [comment]
Might be a good argument for making app_name an.. argument :)

**Comment by jimdineen** [comment]
Perfect thanks!
