### ISSUE TITLE
Error running python deploy-to-lambda.py

### ISSUE THREAD

**Issue by Xtropy74** [m0ngr31/kodi-alexa#58]
Just upgraded to the latest version and trying to run the 

> python deploy-to-lambda.py

 command and getting a crash:

building 'Levenshtein._levenshtein' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/Levenshtein

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c Levenshtein/_levenshtein.c -o build/temp.linux-x86_64-2.7/Levenshtein/_levenshtein.o

Levenshtein/_levenshtein.c:99:20: fatal error: Python.h: No such file or directory

 #include <Python.h>

                    ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_xxxxx/python-Levenshtein/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-MOZqaw-record/install-record.txt --single-version-externally-managed --compile --home=/tmp/tmpPtk0sw failed with error code 1 in /tmp/pip_build_xxxxxpython-Levenshtein

**Comment by jingai** [comment]
You likely don't have the Python development package installed.  If your OS is Debian-like, it should be called "python-dev".

**Comment by Xtropy74** [comment]
Thanks, I guess this is a new requirement because I didn't need it until today?

`apt-get install python-dev` installed ok and I was able to update. Can this be added to requirements.txt as this package is not listed as a requirement anywhere in the changelog/README?

Thanks again for your support with my issues, much appreciated :)

**Comment by jingai** [comment]
If you add the package "python-fuzzywuzzy" it might not need to compile it.  "python-dev" is not a Python module per se, so it doesn't belong in requirements.txt.  It's just a standard Linux practice to make development packages separate.

But yes, it's a new addition.  @jagsta added fuzzy string matching to better match what Alexa hears to the content in your library.

Don't forget to update the utterances and intents in your skill, too!

**Comment by jagsta** [comment]
I'm a bit concerned there have already been a couple of people experiencing build issues as a result of the inclusion of python-Levenshtein, I guess it's not uncommon for people to be lacking python headers, especially on windows. 

Is it worth me adding a reference to the requirements for this module to the README and possibly even remove it from or comment it out of requirements.txt so it's an opt-in? The fuzzy matching will work without the module, it'll just be slower. It will probably result in less requests for help in the project thread on the Kodi forums.

**Comment by jingai** [comment]
Yeah, I was thinking the same. 

I'd say remove from requirements.txt but add a comment about it in the README for those willing to go the extra mile for the optimization.
