### ISSUE TITLE
python-Levenshtein is C based and doesn't install on AWS

### ISSUE THREAD

**Issue by digiltd** [m0ngr31/kodi-alexa#59]
I was getting this warning when I did any searching

```
warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
```

It doesn't appear to affect the fuzzy searching. Testing with __are tehre any new episodes of bubs bougers__ reports back __There is one unseen episode of bubs bougers__

The problem is `python-Levenshtein` is a wrapper for a Levenshtein C Lib. Whilst it appears possible though a lot of faffing to [install it on AWS](http://www.perrygeo.com/running-python-with-compiled-code-on-aws-lambda.html) I don't think it is worth it.

@jagsta @jingai Curious to know if there is any difference in speed locally with and without the `python-Levenshtein` dependency?

On AWS the __bubs bougers__ test from start to finish took 668.68 ms with a library of 35 shows. and  __is there a new episode of the flushe__ took 714.42 ms

**Comment by jingai** [comment]
I honestly haven't tested without it, but the author of fuzzywuzzy at least claims there's a difference, which I'm sure there is. I don't know how much, though I was already discussing with @jagsta about removing it as a requirement and documenting it in the README for those that want (and can install) the optimization. 

For reference,  the other discussion was taking place under Issue #58.

**Comment by jagsta** [comment]
The speed differences are going to be determined by the size of the library you're matching against I guess, for people with many hundreds or even thousands of albums or movies, the difference may become noticeable. The code I added to matchHeard will also as a worst case run 4 sequential attempts to match, which in your case is only 200ms of additional latency but would be worse with larger libraries. With that said I didn't benchmark the two methods so it's possible it's not significant with the sizes of typical Kodi libraries.

I'm submitting a PR shortly to remove it as a standard requirement to allow people to opt-in if they want or need to. Thanks for flagging the issue with AWS, I run the skill locally so hadn't realised that was a problem.

**Comment by jingai** [comment]
It will become more of a concern later when we allow querying the library for content without the media type qualifier -- e.g., "Alexa, play The Big Lebowski" instead of "Alexa, play the movie The Big Lebowski".  I intend to do this at some point, but we can deal with any potential optimization then. 

I don't think it's a major concern at this moment in time.

**Comment by jagsta** [comment]
I've submitted #60 to make this optional

**Comment by jingai** [comment]
PR #60 merged, so I'm closing this.  Thanks for the report.
