### ISSUE TITLE
An error occured (InvalidSignatureException) when calling CreateFunction operation: Signature expired: 20161127T140255Z  is now earlier than 20161127T141105Z

### ISSUE THREAD

**Issue by ghost** [m0ngr31/kodi-alexa#69]
I've been trying to deploy this to AWS for days now after getting my amazon echo here in the Philippines. But I cant get it to work. I have followed every step but every time I run C:\Python27\Scripts\lambda-deploy.exe deploy. I always get this message. I have little knowledge about this and I badly want this to work. I hope someone can help me fix this problem. Thanks!

**Comment by danielmasur** [comment]
Is your local windows clock skewed?

**Comment by ghost** [comment]
I think so. But I followed all tips that I managed to search online to fix it but im not getting any luck. I saw something about adding a code "clockskew" but I dont know where to put it

**Comment by danielmasur** [comment]
What I'm really saying is: Does your windows clock show the correct time? If not set it to the right time.

**Comment by ghost** [comment]
actually it does. do i need to change my timezone to make sure I am sync with the server. My timezone is UTC +8:00

**Comment by Xaelias** [comment]
No shouldn't be an issue. Computers talk to each other in UTC usually (so without timezone).
But you do have an 8-minutes delta.
Do you remember if it was 22:03 or 22:11 when you ran that code? (or just run again and tell us which timestamp is the closest to the actual time.)

**Comment by ghost** [comment]
I tried adjusting my time based on the difference of the 2 time on the error message that I got, and voila it worked! Thank you Sir ausweider & Xaelias!

**Comment by atido** [comment]
Hello, I have the same problem as  "luel87", could you help me to fix it ? I tried both on Mac and Windows and I have always the same error "Signature expired". How to adjust my time based on the difference of 2 time like "luel87" dit it ?
Thanks for your help.

**Comment by ghost** [comment]
All you have to do is to adjust your clock and make sure that your device clock is in sync with the server. You can check the see the time by looking at the error message and adjust it accordingly

**Comment by atido** [comment]
Thank you it works :-)  So strange that we have to manually adjust the clock to get it work.
