### ISSUE TITLE
Warning: use LAMBDA_ENV_VARS instead ?

### ISSUE THREAD

**Issue by OliPassey** [m0ngr31/kodi-alexa#72]
First off, thanks for a great solution - i have AWS knowledge from work so this wasn't too much to get my head around but we don't use Lambda...

Everything is working when i don't use a password on my kodi webserver. When i enabled the password that is set in the env file - i get Alexa failing to control and she says - There was a problem with the expected skills response.

When i set things up i got this error - but seeing as it clearly picked up my hostname and port etc i figured it was erroneous. I've now enabled the password again, and re-deployed, but same error and alexa says the same thing.

WARNING:lambda_deploy: Skipping inclusion of of .env file - use LAMBDA_ENV_VARS instead (see documentation for more information)

Im looking for the documentation for LAMBDA_ENV_VARS but failing. Can you point me in the right direction?

**Comment by jingai** [comment]
You can ignore that warning.  It's mostly just telling you that it's not going to upload your .env file, for security/privacy reasons.  It will make use of it for the configuration still though.

As for your actual issue, I assume you've made sure the passwords match.  I don't think this would be a problem, but does your password contain any symbols (non-alphanumeric characters)?  Have you tried a different password?

**Comment by OliPassey** [comment]
I did have a special character, but i've removed it for testing.  Passwords definetly match.
Still no luck tho.
I've also set the environment variables from the Lambda GUI - i'll remove those :)
Where can i find logs to see what error is returned?
Alexa App says: The target Lambda application returned a failure response

I'll try a completely different password to be sure.

**Comment by jingai** [comment]
The skills logs should be accessible somewhere on the AWS console (sorry, I don't use it myself, so I'm not sure where exactly).

Also, for future reference, when you need support, please start with a post to the [forum thread](http://forum.kodi.tv/showthread.php?tid=254502), unless you're positive you've found a bug or are requesting a feature.

**Comment by OliPassey** [comment]
Thanks - will do. Feel free to remove this thread for cleanliness.
I'll start a new thread if im unable to resolve in the right place

**Comment by jingai** [comment]
It's already here, so we can finish here for now.  Was just letting you know for the future :)

**Comment by digiltd** [comment]
See my post https://github.com/m0ngr31/kodi-alexa/issues/50#issuecomment-257090417 for details of how to access your logs.

I now use https://github.com/jorgebastida/awslogs so I can tail logs in a local terminal.  It is harder to set up, whilst I do recommend it, I can't provide any support for it.

**Comment by jingai** [comment]
Still there, or should I close this, @OliPassey ?

**Comment by OliPassey** [comment]
Go ahead and close - many thanks for the assistance.
