### ISSUE TITLE
Verbiage request: Add "newest" as a substitute for "latest"

### ISSUE THREAD

**Issue by 40wattrange** [m0ngr31/kodi-alexa#74]
Would like to request that the word "newest" be added to equate to "latest"

IE: "Alexa, tell the media center to play the NEWEST episode of the flash"

Currently that phrase will error, but if repeated with LATEST, will go through fine.

**Comment by jingai** [comment]
This is already in the utterances file and it works here.

Maybe you need to update your copy?

**Comment by 40wattrange** [comment]
Was on an older version. Updated a couple days ago and now this works fine. Will update again tonight to test the cleaning library fix.

**Comment by jingai** [comment]
Ok :)
