### ISSUE TITLE
Add Ubuntu walk through to intro/wiki

### ISSUE THREAD

**Issue by 40wattrange** [m0ngr31/kodi-alexa#75]
Not sure if you want to add this to the various setup methods, but I tend to keep this Ubuntu (Server) walk-through up to date:

http://forum.kodi.tv/showthread.php?tid=254502&pid=2411411#pid2411411

The only things that seem to go out of date are the python dependencies as new ones are added. Whenever I update and see that a new one is required I go ahead and edit the post. As well, if you know any that are no longer required I could remove them.

**Comment by jingai** [comment]
Seems like a good idea to me.

Some feedback though:  you can simplify things a bit by pointing people at [LetsEncrypt](https://www.letsencrypt.org) instead of directing them to create self-signed certs.

**Comment by 40wattrange** [comment]
Sure I can give that a shot. Probably would be better for myself too. Let me dog food the process and test it and fill in the blanks. Main reason I stuck with that method is that it can be a real pain in the ass to get files on/off the server with no gui. Though I guess anyone willing to tackle this themselves should know how to mnt usb drives in Ubuntu Server.

**Comment by jingai** [comment]
Yeah.. I hope you're ready to field support requests from Linux newbies ;)

**Comment by jingai** [comment]
Do you still intend to do this?

**Comment by 40wattrange** [comment]
At some point I do yes. I started dog fooding the walk through I had. I tried to take your idea of using Lets Encrypt, but its a hassle due to the expiration of certs every 90 days, so you have to manually flip everything. Personally im not into that portion of it myself. Probably could automate it on the linux side, but having it update Amazon has to take place manually. 

As well I tried to flip the SHA1 to SHA256, but it may have caused some issues. I've been extremely busy in my personal life as of late, so just havent had the time to sit down and figure it all out again. It's to the point where it's not even working in my house anymore.

Also seems like the dev is focusing around cloud hosted solutions, and slowly is making local install more and more of a hassle, and harder to update without having to go edit files every time you pull the updates, not to mention no sort of auto update ability - its alllll manual.

To be upfront too, I've become a docker fan lately. I'm waiting for VMware to update their VIC instance for ESXi ([around April sometime](https://github.com/vmware/vic/projects/1)), and at that point I'm just going to run the containerized version of it. At that point I dont know if Ill be updating it myself, someone else updating the docker or what. I guess thats just a bridge I have to cross when I get there. If I'm maintaining some sort of container im sure all the instruction set would be the same once in the container, so I could update it.

As well, Logitech released a new Harmony skill for Alexas which actually controls a lot of the basic function now (play/pause/stop/increase-decrease volume/etc..) and is universal across my entire media setup, rather than just limited to Kodi. At this point, for me personally, this app is now just for information, random selection of media to play, and direct jumping to media. (which is why i have been slacking on getting it back up and running at home).

I'll try to jump on it this weekend though. I'll have some free time and have been missing the features i'd still need.

EDIT: If needed someone can just copy and paste what I have into the wiki. Last time I checked it worked, but again, some stuff could have changed from now and then as it has been a month and a week since I last looked at it.

**Comment by jingai** [comment]
Just FYI,

> I tried to take your idea of using Lets Encrypt, but its a hassle due to the expiration of certs every 90 days, so you have to manually flip everything. Personally im not into that portion of it myself. Probably could automate it on the linux side, but having it update Amazon has to take place manually.

There is nothing to update on Amazon if you use a CA like Let's Encrypt.  You only have to do that for self-signed certs.

**Comment by 40wattrange** [comment]
Cloudy here on the setup, and haven't played with LE that much - so does it just create the public intermediate file, and that is placed on amazon, so that will never change? And then it's just the private key on the local server that will change, but take place [via the apps they have to auto update](https://certbot.eff.org/). I'll admit I'm pretty ignorant to their setup and workings as I haven't really played with it.

**Comment by jingai** [comment]
You don't place anything on Amazon.  You install the certificate on your web server (Apache, etc) and you're done.

To make it easier to understand.. when you visit https://www.google.com/, for instance, do you manually do anything with the certificate?  No?  That's what CAs are for :)

**Comment by 40wattrange** [comment]
Oh ok. How does amazon make the connection then? You are required to enter a cert on amazon when making the skill, and it wont let you past this.

**Comment by jingai** [comment]
No you are not -- you only manually enter a cert if the endpoint doesn't have a valid CA-signed cert.

In other words, you're only seeing that at all *because* you're using self-signed certs.

**Comment by 40wattrange** [comment]
Ahh ok, very good to know. Man that prboably will make this so much easier. I'll see what I can do through the week/weekend and get back to yah.

Thanks for the info.

**Comment by jingai** [comment]
Going to close this.. a guide wouldn't be unwelcome, but I don't think it's something we'd want to maintain in here, and no one has really stepped up to offer to support it.
