### ISSUE TITLE
Question: Google Home

### ISSUE THREAD

**Issue by oktane83** [m0ngr31/kodi-alexa#76]
Any chance of this being ported to use with Google Home?

Cheers!

**Comment by Xaelias** [comment]
Google Home is not even open to developers yet.

**Comment by jingai** [comment]
Anyone is free to port it when Home opens up to developers.

Your question isn't a bug report or feature request though.  This sort of thing should be posted to [the forum](http://forum.kodi.tv/showthread.php?tid=254502).
