### ISSUE TITLE
Slot generator can't validate my kodi server info

### ISSUE THREAD

**Issue by trumad** [m0ngr31/kodi-alexa#78]
Hey, sorry if this isn't the right place to post this, but I've been banging my head off a brick wall with https://slot-generator.herokuapp.com/ and also with generate_custom_slots.py. Neither can connect to my kodi server.

Now obviously the assumption would be that I haven't set up my kodi webserver properly, but I'm 99% certain I have. It's on port 8080, it's definitely accessible from the internet (I used an open port checker tool and I've visited the page via a VPN), I've tried with both my ip and with my dynamic DNS address. I can access the /jsonrpc file on the server. The python script generate_custom_slots.py just keeps sending request to that file with no success. It does this even if I define the kodi server address as an internal ip and disable credentials completely.

As for the slot generator site, it says "Please validate your server information and try again" no matter what. This also happens when I disable credentials.

Is there anything I haven't tried?

**Comment by trumad** [comment]
Oh...never mind then. Looks like it was something I'm doing wrong. I tested using another kodi box I have and that one works fine. Perhaps it's just a dopey network issue. I'll post here if I get to the bottom of what caused the issue, but I'm guessing some more tinkering will get the original kodi box working. They both have the same shows anyway, so the results from this one can be used to generate slots. Cheers

**Comment by trumad** [comment]
@jingai - I narrowed down exactly what the problem is. The music library on one kodi box is huge, and non-existent on the other. On the one with all the music, slot generator gives the "please validate your server info" error. The empty one works fine.

But if I import my music to the empty kodi, making it as full as the other one, slot generator gives the error. Removing the music again makes it work immediately.

Can anything be done for people with large libraries? If not, I'm happy to let alexa simply play random music. I'll have to test if she plays music from the entire collection, or just from the list I specify in slots... Thanks!

As below, I've moved this issue to the slot generator section.

**Comment by GrahamTheCoder** [comment]
I had a very similar symptom (and found this thread when looking for a result), therefore I thought I'd mention that putting a `#` in your password for kodi will break the deployment process. In retrospect, it's obvious since it will treat the `#` as the start of a comment, and ignore it (and anything else after it on that line). There's probably an escape character...I just changed my kodi password to remove the `#` and updated the config file.
