### ISSUE TITLE
Party Mode fails with a large song library

### ISSUE THREAD

**Issue by jingai** [m0ngr31/kodi-alexa#80]
Might be better to use the PartyMode option with Player.Open()

**Comment by m0ngr31** [comment]
Can you elaborate?

**Comment by jingai** [comment]
Sorry, didn't mean to leave this with so little info -- was in the middle of other things when I created the Issue (just so I wouldn't forget about it).  I'll post back in a bit with more info.

**Comment by m0ngr31** [comment]
Cool

**Comment by m0ngr31** [comment]
I see what you mean now. I have this fixed locally and will merge it with the new flask-ask branch.
