### ISSUE TITLE
lambda-deploy fails due to incorrectly named .env file

### ISSUE THREAD

**Issue by ScriptSorcererUK** [m0ngr31/kodi-alexa#86]
the lambda-deploy file fails because it is looking for a file called .env - not .env.lambda , I figured it out and renamed the file, and I'm sure there is a good reason for having the two .env files so you can switch between them, but your install guide should recommend renaming one of the files to .env in order for it to work (in windows you have to do this in the command prompt - not explorer.

**Comment by devdems** [comment]
This is correct. If you check instructions you will see that you have to make .env file from .env.lambda. This issue can be closed.

**Comment by ScriptSorcererUK** [comment]
Thanks. I didn't see the line of text in the readme.
> The environment variables are stored in an .env file which you need to create yourself from a copy of .env.lambda

 I think it would be helpful to many first time users if it was emphasized more in the readme and maybe more detail added to explain what they need to do. Also, an error message built into the deploy code to say "you don't have a .env file, are you sure you want to proceed without it or would you like to use the file .env.lamdba that I found?" Not a huge amount of work to add...

**Comment by jingai** [comment]
It states that you need to copy .env.lambda to .env and then edit it.  What else should it say?
