### ISSUE TITLE
no connection

### ISSUE THREAD

**Issue by blairn64** [m0ngr31/kodi-alexa#91]
i have enabled ports on my router and can access my kodi server from a ddns address 
I have set up the .env file with my kodi server address, port number, user name and password, and have set the AWS_DEFAULT_REGION = eu-west-1 

i deployed the code via cmd and my function was in the aws console under lambda i have my kodi-alexa function which has the role lambda and triggers set to the Alexa Skills Kit, the arn i got from this page was then copy and pasted into the AWS Lambda ARN (Amazon Resource Name) box under the endpoint field in the amazon development console 

i filled out the Skill Information page with the name kodi and invocation name of the living room 
Interaction Model i created the slots and copy and pasted the invocations and the intents in the configuration page is where i pasted the arn and selected the europe checkbox then put the Publishing Information and done the Privacy & Compliance page 

i now see the kodi app under alexa skills > my skills and i can enable it but there is no interactions between alexa and the living room whenever i ask alexa to play/pause/stop navigate etc she replys with either "i could not fing the livingroom under my account" or "sorry something went wrong" is there any way to tell what iv done wrong or how to find out if alexa is communicating correctly and its my accent or invocation name or have i just bummed up somewhere? ichanged the invocation name to winchester alexa is picking up what im saying "ask winchester to navigate left" in the alexa app but nothing happens

**Comment by digiltd** [comment]
It is hard to know where to start as I am guessing you don't either.

The best place for advice would be the thread on the [Kodi forum](http://forum.kodi.tv/showthread.php?tid=254502)

I know it is a faff but have a read through all the pages, it will start to make sense as you become more familiar with it :)

**Comment by blairn64** [comment]
turned out the app was set to united states s as default i just copied all the code and created under u.k!
fantastic build 🥇  @m0ngr31 🥇  absolutely amazing work! and thanks for helping me get this set up @digiltd. cheers guys ill close this now
