### ISSUE TITLE
Document upgrade procedure

### ISSUE THREAD

**Issue by jingai** [m0ngr31/kodi-alexa#93]
The README illustrates pretty well how to install the skill from scratch, but a lot of users are confused about what they need to do when upgrading.

We should add a section in the README to specifically address the steps necessary to upgrade the skill when the code base has changed.

**Comment by jingai** [comment]
Looks like this is covered by 6859197, right @m0ngr31?

**Comment by m0ngr31** [comment]
Yeah, I think so.
