### ISSUE TITLE
Slot generator needs to remove quotes

### ISSUE THREAD

**Issue by jingai** [m0ngr31/kodi-alexa#97]
Not allowed by Amazon

**Comment by digiltd** [comment]
What about when a single quote is used for possessives?

If it helps I started trying to work out a way to detect and keep apostrophes when used for possessives. This was before the recent changes (adding a 'sanitize_name' function) to accommodate the German translations. It was getting too messy so I stopped working it

Here is the regex I was working on

https://regex101.com/r/NsK8ym/1

Some relevant SO discussions :

http://stackoverflow.com/questions/5515340/regex-to-allow-apostrophe-only-in-words-ending-with-s
http://stackoverflow.com/questions/2596893/regex-to-match-words-and-those-with-an-apostrophe

**Comment by jingai** [comment]
This only applies to double quotes, I thought?

**Comment by digiltd** [comment]
The usual [hazy docs](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interaction-model-reference#h2_custom_syntax) suggest no punctuation at all, apart from the special cases listed in **Rules for Sample Utterances**.

e.g. Full stops (or periods) can be used to identify an acronym e.g. `b. b. c.`

I am not sure if it causes problems, or if it does, shouldn't fuzzy matching handle such issues once that kicks in?

**Comment by jingai** [comment]
Oh I see. Yeah it does say no apostrophes except for possessives.

I doubt it would actually cause matches to fail, but we might still want to adhere to the rules.

**Comment by jingai** [comment]
It *probably* would work with possessives if we just removed all quotes, rather than trying to trim them smartly.. but it'd require some testing.

**Comment by jingai** [comment]
I'd say move forward just removing single and double quotes.

edit: Or, just remove only double quotes and let single quotes through until we can figure a more elegant way around this.  IIRC, single quotes at least don't cause the skill to error on save.

**Comment by m0ngr31** [comment]
Resolved on `flask-ask` branch.
