### ISSUE TITLE
Slot generator needs to limit items to 140 characters

### ISSUE THREAD

**Issue by jingai** [m0ngr31/kodi-alexa#98]
Limit imposed by Amazon

**Comment by m0ngr31** [comment]
What do you think the best solution would be? Straight truncation?

**Comment by jingai** [comment]
Yeah, I don't think I'd try to get any more clever than that.  It's not as if someone is going to actually speak the whole thing anyway if it's really that long.

**Comment by m0ngr31** [comment]
Alright, I'll get the slot generators updated.

**Comment by jingai** [comment]
The only thing I'd probably do is cut to the nearest delimiter (i.e., space, hyphen, etc), so we're not truncating words.

**Comment by m0ngr31** [comment]
This is fixed on the web based slot generator and the flask-ask branch version
